workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    KSeF API TE:
        inputs:
            - location: openapi.yaml
        overlays:
            - location: .speakeasy\speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/intermedia/ksef-wpw/k-se-f-api-te
targets:
    ksef1:
        target: php
        source: KSeF API TE
        publish:
            packagist:
                username: $packagist_username
                token: $packagist_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/intermedia/ksef-wpw/k-se-f-api-te-php-code-samples
            labelOverride:
                fixedValue: Php (SDK)
            blocking: false
