<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


class AddAttachmentRequest
{
    /**
     *
     * @var string $nip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nip')]
    public string $nip;

    /**
     * @param  string  $nip
     * @phpstan-pure
     */
    public function __construct(string $nip)
    {
        $this->nip = $nip;
    }
}