<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


/** AllowedIps - Lista dozwolonych adresów IP. */
class AllowedIps
{
    /**
     * Lista adresów IPv4 w notacji dziesiętnej kropkowanej, np. `192.168.0.10`.
     *
     * @var ?array<string> $ipAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ipAddress')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $ipAddress = null;

    /**
     * Lista adresów IPv4 podana w formie zakresu początek–koniec, oddzielonego pojedynczym myślnikiem, np. `10.0.0.1–10.0.0.254`.
     *
     * @var ?array<string> $ipRange
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ipRange')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $ipRange = null;

    /**
     * Lista adresów IPv4 w notacji CIDR z maską 8 / 16 / 24 / 32, np. `172.16.0.0/16`.
     *
     * @var ?array<string> $ipMask
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ipMask')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $ipMask = null;

    /**
     * @param  ?array<string>  $ipAddress
     * @param  ?array<string>  $ipRange
     * @param  ?array<string>  $ipMask
     * @phpstan-pure
     */
    public function __construct(?array $ipAddress = null, ?array $ipRange = null, ?array $ipMask = null)
    {
        $this->ipAddress = $ipAddress;
        $this->ipRange = $ipRange;
        $this->ipMask = $ipMask;
    }
}