<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
class AssignPermissionsRequest
{
    /**
     *
     * @var AssignPermissionsContextIdentifier $contextIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contextIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\AssignPermissionsContextIdentifier')]
    public AssignPermissionsContextIdentifier $contextIdentifier;

    /**
     *
     * @var AssignPermissionsAuthorizedIdentifier $authorizedIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorizedIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\AssignPermissionsAuthorizedIdentifier')]
    public AssignPermissionsAuthorizedIdentifier $authorizedIdentifier;

    /**
     * $permissions
     *
     * @var array<Components\TestDataPermission> $permissions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permissions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\TestDataPermission>')]
    public array $permissions;

    /**
     * @param  AssignPermissionsContextIdentifier  $contextIdentifier
     * @param  AssignPermissionsAuthorizedIdentifier  $authorizedIdentifier
     * @param  array<Components\TestDataPermission>  $permissions
     * @phpstan-pure
     */
    public function __construct(AssignPermissionsContextIdentifier $contextIdentifier, AssignPermissionsAuthorizedIdentifier $authorizedIdentifier, array $permissions)
    {
        $this->contextIdentifier = $contextIdentifier;
        $this->authorizedIdentifier = $authorizedIdentifier;
        $this->permissions = $permissions;
    }
}