<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
class AssignPermissionsContextIdentifier
{
    /**
     *
     * @var Components\TestDataContextIdentifierType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\TestDataContextIdentifierType')]
    public Components\TestDataContextIdentifierType $type;

    /**
     *
     * @var string $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    public string $value;

    /**
     * @param  Components\TestDataContextIdentifierType  $type
     * @param  string  $value
     * @phpstan-pure
     */
    public function __construct(Components\TestDataContextIdentifierType $type, string $value)
    {
        $this->type = $type;
        $this->value = $value;
    }
}