<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


/** BatchSession - Limity dla sesji wsadowych. */
class BatchSession
{
    /**
     * Maksymalny rozmiar faktury w MiB.
     *
     * @var int $maxInvoiceSizeInMib
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('maxInvoiceSizeInMib')]
    public int $maxInvoiceSizeInMib;

    /**
     * Maksymalny rozmiar faktury z załącznikiem w MiB.
     *
     * @var int $maxInvoiceWithAttachmentSizeInMib
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('maxInvoiceWithAttachmentSizeInMib')]
    public int $maxInvoiceWithAttachmentSizeInMib;

    /**
     * Maksymalna ilość faktur które można przesłać w pojedynczej sesji.
     *
     * @var int $maxInvoices
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('maxInvoices')]
    public int $maxInvoices;

    /**
     * @param  int  $maxInvoiceSizeInMib
     * @param  int  $maxInvoiceWithAttachmentSizeInMib
     * @param  int  $maxInvoices
     * @phpstan-pure
     */
    public function __construct(int $maxInvoiceSizeInMib, int $maxInvoiceWithAttachmentSizeInMib, int $maxInvoices)
    {
        $this->maxInvoiceSizeInMib = $maxInvoiceSizeInMib;
        $this->maxInvoiceWithAttachmentSizeInMib = $maxInvoiceWithAttachmentSizeInMib;
        $this->maxInvoices = $maxInvoices;
    }
}