<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
class CreateSubjectRequest
{
    /**
     *
     * @var string $subjectNip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subjectNip')]
    public string $subjectNip;

    /**
     *
     * @var Components\SubjectType $subjectType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subjectType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\SubjectType')]
    public Components\SubjectType $subjectType;

    /**
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * $subunits
     *
     * @var ?array<Components\Subunit> $subunits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subunits')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\Subunit>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $subunits = null;

    /**
     *
     * @var ?\DateTime $createdDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdDate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdDate = null;

    /**
     * @param  string  $subjectNip
     * @param  Components\SubjectType  $subjectType
     * @param  string  $description
     * @param  ?array<Components\Subunit>  $subunits
     * @param  ?\DateTime  $createdDate
     * @phpstan-pure
     */
    public function __construct(string $subjectNip, Components\SubjectType $subjectType, string $description, ?array $subunits = null, ?\DateTime $createdDate = null)
    {
        $this->subjectNip = $subjectNip;
        $this->subjectType = $subjectType;
        $this->description = $description;
        $this->subunits = $subunits;
        $this->createdDate = $createdDate;
    }
}