<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


class CreatePersonRequest
{
    /**
     *
     * @var string $nip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nip')]
    public string $nip;

    /**
     *
     * @var string $pesel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pesel')]
    public string $pesel;

    /**
     *
     * @var bool $isBailiff
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('isBailiff')]
    public bool $isBailiff;

    /**
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     *
     * @var ?\DateTime $createdDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdDate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdDate = null;

    /**
     * @param  string  $nip
     * @param  string  $pesel
     * @param  bool  $isBailiff
     * @param  string  $description
     * @param  ?\DateTime  $createdDate
     * @phpstan-pure
     */
    public function __construct(string $nip, string $pesel, bool $isBailiff, string $description, ?\DateTime $createdDate = null)
    {
        $this->nip = $nip;
        $this->pesel = $pesel;
        $this->isBailiff = $isBailiff;
        $this->description = $description;
        $this->createdDate = $createdDate;
    }
}