<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
/** Filters - Zestaw filtrów do wyszukiwania faktur. */
class Filters
{
    /**
     * Typ podmiotu, którego dotyczą kryteria filtrowania faktur.
     *
     * Określa kontekst, w jakim przeszukiwane są dane.
     * | Wartość | Opis |
     * | --- | --- |
     * | Subject1 | Podmiot 1 |
     * | Subject2 | Podmiot 2 |
     * | Subject3 | Podmiot 3 |
     * | SubjectAuthorized | Podmiot upoważniony |
     *
     *
     * @var Components\InvoiceQuerySubjectType $subjectType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subjectType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\InvoiceQuerySubjectType')]
    public Components\InvoiceQuerySubjectType $subjectType;

    /**
     * Typ i zakres dat, według którego mają być filtrowane faktury.
     *
     * @var PostApiV2InvoicesExportsDateRange $dateRange
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dateRange')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2InvoicesExportsDateRange')]
    public PostApiV2InvoicesExportsDateRange $dateRange;

    /**
     * Numer KSeF faktury.
     *
     * @var ?string $ksefNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ksefNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ksefNumber = null;

    /**
     * Numer faktury nadany przez wystawcę.
     *
     * @var ?string $invoiceNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoiceNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $invoiceNumber = null;

    /**
     * Filtr kwotowy – brutto, netto lub VAT (z wartością).
     *
     * @var ?PostApiV2InvoicesExportsAmount $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2InvoicesExportsAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostApiV2InvoicesExportsAmount $amount = null;

    /**
     * Dane sprzedawcy.
     *
     * @var ?PostApiV2InvoicesExportsSeller $seller
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('seller')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2InvoicesExportsSeller|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostApiV2InvoicesExportsSeller $seller = null;

    /**
     * Dane nabywcy.
     *
     * @var ?PostApiV2InvoicesExportsBuyer $buyer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('buyer')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2InvoicesExportsBuyer|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostApiV2InvoicesExportsBuyer $buyer = null;

    /**
     * Kody walut.
     *
     * @var ?array<Components\CurrencyCode> $currencyCodes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currencyCodes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\CurrencyCode>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $currencyCodes = null;

    /**
     * Tryb wystawienia faktury: online lub offline.
     *
     * @var ?PostApiV2InvoicesExportsInvoicingMode $invoicingMode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoicingMode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2InvoicesExportsInvoicingMode|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostApiV2InvoicesExportsInvoicingMode $invoicingMode = null;

    /**
     * Czy faktura została wystawiona w trybie samofakturowania.
     *
     * @var ?bool $isSelfInvoicing
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('isSelfInvoicing')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isSelfInvoicing = null;

    /**
     * Struktura dokumentu.
     *
     * | Wartość | Opis |
     * | --- | --- |
     * | FA | Faktura VAT |
     * | PEF | Faktura PEF |
     * | RR | Faktura RR |
     *
     *
     * @var ?PostApiV2InvoicesExportsFormType $formType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('formType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2InvoicesExportsFormType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostApiV2InvoicesExportsFormType $formType = null;

    /**
     * Rodzaje faktur.
     *
     * | Wartość | Opis |
     * | --- | --- |
     * | Vat | (FA) Podstawowa |
     * | Zal | (FA) Zaliczkowa |
     * | Kor | (FA) Korygująca |
     * | Roz | (FA) Rozliczeniowa |
     * | Upr | (FA) Uproszczona |
     * | KorZal | (FA) Korygująca fakturę zaliczkową |
     * | KorRoz | (FA) Korygująca fakturę rozliczeniową |
     * | VatPef | [Mock] (PEF) Podstawowowa |
     * | VatPefSp | [Mock] (PEF) Specjalizowana |
     * | KorPef | [Mock] (PEF) Korygująca |
     * | VatRr | [Mock] (RR) Podstawowa |
     * | KorVatRr | [Mock] (RR) Korygująca |
     *
     *
     * @var ?array<Components\InvoiceMetadataInvoiceType> $invoiceTypes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoiceTypes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\InvoiceMetadataInvoiceType>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $invoiceTypes = null;

    /**
     * Czy faktura ma załącznik.
     *
     * @var ?bool $hasAttachment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasAttachment')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $hasAttachment = null;

    /**
     * @param  Components\InvoiceQuerySubjectType  $subjectType
     * @param  PostApiV2InvoicesExportsDateRange  $dateRange
     * @param  ?string  $ksefNumber
     * @param  ?string  $invoiceNumber
     * @param  ?PostApiV2InvoicesExportsAmount  $amount
     * @param  ?PostApiV2InvoicesExportsSeller  $seller
     * @param  ?PostApiV2InvoicesExportsBuyer  $buyer
     * @param  ?array<Components\CurrencyCode>  $currencyCodes
     * @param  ?PostApiV2InvoicesExportsInvoicingMode  $invoicingMode
     * @param  ?bool  $isSelfInvoicing
     * @param  ?PostApiV2InvoicesExportsFormType  $formType
     * @param  ?array<Components\InvoiceMetadataInvoiceType>  $invoiceTypes
     * @param  ?bool  $hasAttachment
     * @phpstan-pure
     */
    public function __construct(Components\InvoiceQuerySubjectType $subjectType, PostApiV2InvoicesExportsDateRange $dateRange, ?string $ksefNumber = null, ?string $invoiceNumber = null, ?PostApiV2InvoicesExportsAmount $amount = null, ?PostApiV2InvoicesExportsSeller $seller = null, ?PostApiV2InvoicesExportsBuyer $buyer = null, ?array $currencyCodes = null, ?PostApiV2InvoicesExportsInvoicingMode $invoicingMode = null, ?bool $isSelfInvoicing = null, ?PostApiV2InvoicesExportsFormType $formType = null, ?array $invoiceTypes = null, ?bool $hasAttachment = null)
    {
        $this->subjectType = $subjectType;
        $this->dateRange = $dateRange;
        $this->ksefNumber = $ksefNumber;
        $this->invoiceNumber = $invoiceNumber;
        $this->amount = $amount;
        $this->seller = $seller;
        $this->buyer = $buyer;
        $this->currencyCodes = $currencyCodes;
        $this->invoicingMode = $invoicingMode;
        $this->isSelfInvoicing = $isSelfInvoicing;
        $this->formType = $formType;
        $this->invoiceTypes = $invoiceTypes;
        $this->hasAttachment = $hasAttachment;
    }
}