<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Utils\SpeakeasyMetadata;
class GetExportStatusRequest
{
    /**
     * Numer referencyjny operacji.
     *
     * @var string $operationReferenceNumber
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=operationReferenceNumber')]
    public string $operationReferenceNumber;

    /**
     * @param  string  $operationReferenceNumber
     * @phpstan-pure
     */
    public function __construct(string $operationReferenceNumber)
    {
        $this->operationReferenceNumber = $operationReferenceNumber;
    }
}