<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Utils\SpeakeasyMetadata;
class GetInvoicesListRequest
{
    /**
     * Zestaw filtrów dla wyszukiwania metadanych.
     *
     * @var ?GetInvoicesListRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?GetInvoicesListRequestBody $requestBody = null;

    /**
     * Indeks pierwszej strony wyników (0 = pierwsza strona).
     *
     * @var ?int $pageOffset
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=pageOffset')]
    public ?int $pageOffset = null;

    /**
     * Rozmiar strony wyników.
     *
     * @var ?int $pageSize
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=pageSize')]
    public ?int $pageSize = null;

    /**
     * @param  ?int  $pageOffset
     * @param  ?int  $pageSize
     * @param  ?GetInvoicesListRequestBody  $requestBody
     * @phpstan-pure
     */
    public function __construct(?GetInvoicesListRequestBody $requestBody = null, ?int $pageOffset = 0, ?int $pageSize = 10)
    {
        $this->requestBody = $requestBody;
        $this->pageOffset = $pageOffset;
        $this->pageSize = $pageSize;
    }
}