<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
class GrantAuthorizationsRequest
{
    /**
     * Identyfikator podmiotu uprawnianego.
     *
     * | Type | Value |
     * | --- | --- |
     * | Nip | 10 cyfrowy numer NIP |
     * | PeppolId | Identyfikator dostawcy usług Peppol |
     *
     * @var GrantAuthorizationsSubjectIdentifier $subjectIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subjectIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\GrantAuthorizationsSubjectIdentifier')]
    public GrantAuthorizationsSubjectIdentifier $subjectIdentifier;

    /**
     * Rodzaj uprawnienia.
     *
     * @var Components\EntityAuthorizationPermissionType $permission
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permission')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\EntityAuthorizationPermissionType')]
    public Components\EntityAuthorizationPermissionType $permission;

    /**
     * Opis uprawnienia
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * @param  GrantAuthorizationsSubjectIdentifier  $subjectIdentifier
     * @param  Components\EntityAuthorizationPermissionType  $permission
     * @param  string  $description
     * @phpstan-pure
     */
    public function __construct(GrantAuthorizationsSubjectIdentifier $subjectIdentifier, Components\EntityAuthorizationPermissionType $permission, string $description)
    {
        $this->subjectIdentifier = $subjectIdentifier;
        $this->permission = $permission;
        $this->description = $description;
    }
}