<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
class GrantToEuEntitiesRequest
{
    /**
     * Identyfikator podmiotu.
     *
     * | Type | Value |
     * | --- | --- |
     * | Fingerprint | Odcisk palca certyfikatu |
     *
     * @var GrantToEuEntitiesSubjectIdentifier $subjectIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subjectIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\GrantToEuEntitiesSubjectIdentifier')]
    public GrantToEuEntitiesSubjectIdentifier $subjectIdentifier;

    /**
     * Lista nadawanych uprawnień. Każda wartość może wystąpić tylko raz.
     *
     * @var array<Components\EuEntityPermissionType> $permissions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permissions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\EuEntityPermissionType>')]
    public array $permissions;

    /**
     * Opis nadawanych uprawnień.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * @param  GrantToEuEntitiesSubjectIdentifier  $subjectIdentifier
     * @param  array<Components\EuEntityPermissionType>  $permissions
     * @param  string  $description
     * @phpstan-pure
     */
    public function __construct(GrantToEuEntitiesSubjectIdentifier $subjectIdentifier, array $permissions, string $description)
    {
        $this->subjectIdentifier = $subjectIdentifier;
        $this->permissions = $permissions;
        $this->description = $description;
    }
}