<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


/**
 * GrantToSubunitsSubjectIdentifier - Identyfikator podmiotu lub osoby fizycznej.
 *
 * | Type | Value |
 * | --- | --- |
 * | Nip | 10 cyfrowy numer NIP |
 * | Pesel | 11 cyfrowy numer PESEL |
 * | Fingerprint | Odcisk palca certyfikatu |
 */
class GrantToSubunitsSubjectIdentifier
{
    /**
     * Typ identyfikatora.
     *
     * @var Type $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\Type')]
    public Type $type;

    /**
     * Wartość identyfikatora.
     *
     * @var string $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    public string $value;

    /**
     * @param  Type  $type
     * @param  string  $value
     * @phpstan-pure
     */
    public function __construct(Type $type, string $value)
    {
        $this->type = $type;
        $this->value = $value;
    }
}