<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


/** IpAddressPolicy - Reguła walidacji adresu IP klienta przy każdym użyciu tokena dostępu. */
class IpAddressPolicy
{
    /**
     * Określa reakcję systemu, gdy token dostępu zostanie użyty z adresu IP spoza zadeklarowanej listy dozwolonych adresów IP (allowedIps).
     *
     * @var ?OnClientIpChange $onClientIpChange
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('onClientIpChange')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\OnClientIpChange|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?OnClientIpChange $onClientIpChange = null;

    /**
     * Lista dozwolonych adresów IP.
     *
     * @var ?AllowedIps $allowedIps
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allowedIps')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\AllowedIps|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AllowedIps $allowedIps = null;

    /**
     * @param  ?OnClientIpChange  $onClientIpChange
     * @param  ?AllowedIps  $allowedIps
     * @phpstan-pure
     */
    public function __construct(?OnClientIpChange $onClientIpChange = null, ?AllowedIps $allowedIps = null)
    {
        $this->onClientIpChange = $onClientIpChange;
        $this->allowedIps = $allowedIps;
    }
}