<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


class OnlineSessionOpenRequest
{
    /**
     * Schemat faktur wysyłanych w ramach sesji.
     *
     *
     * Obsługiwane schematy:
     * | SystemCode | SchemaVersion | Value |
     * | --- | --- | --- |
     * | FA (2) | 1-0E | FA |
     * | FA (3) | 1-0E | FA |
     * | FA_PEF (3) | 2-1 | FA_PEF |
     * | FA_KOR_PEF (3) | 2-1 | FA_PEF |
     *
     *
     * @var OnlineSessionOpenFormCode $formCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('formCode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\OnlineSessionOpenFormCode')]
    public OnlineSessionOpenFormCode $formCode;

    /**
     * Symetryczny klucz szyfrujący pliki XML, zaszyfrowany kluczem publicznym Ministerstwa Finansów.
     *
     * @var OnlineSessionOpenEncryption $encryption
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('encryption')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\OnlineSessionOpenEncryption')]
    public OnlineSessionOpenEncryption $encryption;

    /**
     * @param  OnlineSessionOpenFormCode  $formCode
     * @param  OnlineSessionOpenEncryption  $encryption
     * @phpstan-pure
     */
    public function __construct(OnlineSessionOpenFormCode $formCode, OnlineSessionOpenEncryption $encryption)
    {
        $this->formCode = $formCode;
        $this->encryption = $encryption;
    }
}