<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
/** PostApiV2InvoicesQueryMetadataRequestBody - Zestaw filtrów dla wyszukiwania metadanych. */
class PostApiV2InvoicesQueryMetadataRequestBody
{
    /**
     * Typ podmiotu, którego dotyczą kryteria filtrowania metadanych faktur.
     *
     * Określa kontekst, w jakim przeszukiwane są dane.
     * | Wartość | Opis |
     * | --- | --- |
     * | Subject1 | Podmiot 1 |
     * | Subject2 | Podmiot 2 |
     * | Subject3 | Podmiot 3 |
     * | SubjectAuthorized | Podmiot upoważniony |
     *
     *
     * @var Components\InvoiceQuerySubjectType $subjectType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subjectType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\InvoiceQuerySubjectType')]
    public Components\InvoiceQuerySubjectType $subjectType;

    /**
     * Typ i zakres dat, według którego mają być filtrowane faktury. Dozwolony maksymalny okres wynosi 2 lata.
     *
     * @var PostApiV2InvoicesQueryMetadataDateRange $dateRange
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dateRange')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2InvoicesQueryMetadataDateRange')]
    public PostApiV2InvoicesQueryMetadataDateRange $dateRange;

    /**
     * Numer KSeF faktury.
     *
     * @var ?string $ksefNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ksefNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ksefNumber = null;

    /**
     * Numer faktury nadany przez wystawcę.
     *
     * @var ?string $invoiceNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoiceNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $invoiceNumber = null;

    /**
     * Filtr kwotowy – brutto, netto lub VAT (z wartością).
     *
     * @var ?PostApiV2InvoicesQueryMetadataAmount $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2InvoicesQueryMetadataAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostApiV2InvoicesQueryMetadataAmount $amount = null;

    /**
     * Nip sprzedawcy.
     *
     * @var ?string $sellerNip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sellerNip')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $sellerNip = null;

    /**
     * Identyfikator nabywcy.
     *
     * @var ?PostApiV2InvoicesQueryMetadataBuyerIdentifier $buyerIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('buyerIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2InvoicesQueryMetadataBuyerIdentifier|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostApiV2InvoicesQueryMetadataBuyerIdentifier $buyerIdentifier = null;

    /**
     * Kody walut.
     *
     * @var ?array<Components\CurrencyCode> $currencyCodes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currencyCodes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\CurrencyCode>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $currencyCodes = null;

    /**
     * Tryb wystawienia faktury: online lub offline.
     *
     * @var ?PostApiV2InvoicesQueryMetadataInvoicingMode $invoicingMode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoicingMode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2InvoicesQueryMetadataInvoicingMode|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostApiV2InvoicesQueryMetadataInvoicingMode $invoicingMode = null;

    /**
     * Czy faktura została wystawiona w trybie samofakturowania.
     *
     * @var ?bool $isSelfInvoicing
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('isSelfInvoicing')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isSelfInvoicing = null;

    /**
     * Typ dokumentu.
     *
     * | Wartość | Opis |
     * | --- | --- |
     * | FA | Faktura VAT |
     * | PEF | Faktura PEF |
     * | RR | Faktura RR |
     *
     *
     * @var ?PostApiV2InvoicesQueryMetadataFormType $formType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('formType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2InvoicesQueryMetadataFormType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostApiV2InvoicesQueryMetadataFormType $formType = null;

    /**
     * Rodzaje faktur.
     *
     * | Wartość | Opis |
     * | --- | --- |
     * | Vat | (FA) Podstawowa |
     * | Zal | (FA) Zaliczkowa |
     * | Kor | (FA) Korygująca |
     * | Roz | (FA) Rozliczeniowa |
     * | Upr | (FA) Uproszczona |
     * | KorZal | (FA) Korygująca fakturę zaliczkową |
     * | KorRoz | (FA) Korygująca fakturę rozliczeniową |
     * | VatPef | (PEF) Podstawowowa |
     * | VatPefSp | (PEF) Specjalizowana |
     * | KorPef | (PEF) Korygująca |
     * | VatRr | (RR) Podstawowa |
     * | KorVatRr | (RR) Korygująca |
     *
     *
     * @var ?array<Components\InvoiceType> $invoiceTypes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoiceTypes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\InvoiceType>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $invoiceTypes = null;

    /**
     * Czy faktura ma załącznik.
     *
     * @var ?bool $hasAttachment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasAttachment')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $hasAttachment = null;

    /**
     * @param  Components\InvoiceQuerySubjectType  $subjectType
     * @param  PostApiV2InvoicesQueryMetadataDateRange  $dateRange
     * @param  ?string  $ksefNumber
     * @param  ?string  $invoiceNumber
     * @param  ?PostApiV2InvoicesQueryMetadataAmount  $amount
     * @param  ?string  $sellerNip
     * @param  ?PostApiV2InvoicesQueryMetadataBuyerIdentifier  $buyerIdentifier
     * @param  ?array<Components\CurrencyCode>  $currencyCodes
     * @param  ?PostApiV2InvoicesQueryMetadataInvoicingMode  $invoicingMode
     * @param  ?bool  $isSelfInvoicing
     * @param  ?PostApiV2InvoicesQueryMetadataFormType  $formType
     * @param  ?array<Components\InvoiceType>  $invoiceTypes
     * @param  ?bool  $hasAttachment
     * @phpstan-pure
     */
    public function __construct(Components\InvoiceQuerySubjectType $subjectType, PostApiV2InvoicesQueryMetadataDateRange $dateRange, ?string $ksefNumber = null, ?string $invoiceNumber = null, ?PostApiV2InvoicesQueryMetadataAmount $amount = null, ?string $sellerNip = null, ?PostApiV2InvoicesQueryMetadataBuyerIdentifier $buyerIdentifier = null, ?array $currencyCodes = null, ?PostApiV2InvoicesQueryMetadataInvoicingMode $invoicingMode = null, ?bool $isSelfInvoicing = null, ?PostApiV2InvoicesQueryMetadataFormType $formType = null, ?array $invoiceTypes = null, ?bool $hasAttachment = null)
    {
        $this->subjectType = $subjectType;
        $this->dateRange = $dateRange;
        $this->ksefNumber = $ksefNumber;
        $this->invoiceNumber = $invoiceNumber;
        $this->amount = $amount;
        $this->sellerNip = $sellerNip;
        $this->buyerIdentifier = $buyerIdentifier;
        $this->currencyCodes = $currencyCodes;
        $this->invoicingMode = $invoicingMode;
        $this->isSelfInvoicing = $isSelfInvoicing;
        $this->formType = $formType;
        $this->invoiceTypes = $invoiceTypes;
        $this->hasAttachment = $hasAttachment;
    }
}