<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


class PostApiV2PermissionsSubunitsGrantsRequest
{
    /**
     * Identyfikator podmiotu lub osoby fizycznej.
     *
     * | Type | Value |
     * | --- | --- |
     * | Nip | 10 cyfrowy numer NIP |
     * | Pesel | 11 cyfrowy numer PESEL |
     * | Fingerprint | Odcisk palca certyfikatu |
     *
     * @var PostApiV2PermissionsSubunitsGrantsSubjectIdentifier $subjectIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subjectIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2PermissionsSubunitsGrantsSubjectIdentifier')]
    public PostApiV2PermissionsSubunitsGrantsSubjectIdentifier $subjectIdentifier;

    /**
     * Identyfikator podmiotu podrzędnego.
     *
     * | Type | Value |
     * | --- | --- |
     * | Nip | 10 cyfrowy numer NIP |
     * | InternalId | Dwuczłonowy identyfikator składający się z numeru NIP i 5 cyfr: `{nip}-{5_cyfr}` |
     *
     * @var PostApiV2PermissionsSubunitsGrantsContextIdentifier $contextIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contextIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2PermissionsSubunitsGrantsContextIdentifier')]
    public PostApiV2PermissionsSubunitsGrantsContextIdentifier $contextIdentifier;

    /**
     * Opis nadawanych uprawnień.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * @param  PostApiV2PermissionsSubunitsGrantsSubjectIdentifier  $subjectIdentifier
     * @param  PostApiV2PermissionsSubunitsGrantsContextIdentifier  $contextIdentifier
     * @param  string  $description
     * @phpstan-pure
     */
    public function __construct(PostApiV2PermissionsSubunitsGrantsSubjectIdentifier $subjectIdentifier, PostApiV2PermissionsSubunitsGrantsContextIdentifier $contextIdentifier, string $description)
    {
        $this->subjectIdentifier = $subjectIdentifier;
        $this->contextIdentifier = $contextIdentifier;
        $this->description = $description;
    }
}