<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Utils\SpeakeasyMetadata;
class PostApiV2SessionsOnlineReferenceNumberInvoicesRequest
{
    /**
     * Numer referencyjny sesji
     *
     * @var string $referenceNumber
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=referenceNumber')]
    public string $referenceNumber;

    /**
     * Dane faktury
     *
     * @var ?PostApiV2SessionsOnlineReferenceNumberInvoicesRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?PostApiV2SessionsOnlineReferenceNumberInvoicesRequestBody $requestBody = null;

    /**
     * @param  string  $referenceNumber
     * @param  ?PostApiV2SessionsOnlineReferenceNumberInvoicesRequestBody  $requestBody
     * @phpstan-pure
     */
    public function __construct(string $referenceNumber, ?PostApiV2SessionsOnlineReferenceNumberInvoicesRequestBody $requestBody = null)
    {
        $this->referenceNumber = $referenceNumber;
        $this->requestBody = $requestBody;
    }
}