<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


class PostApiV2InvoicesExportsRequest
{
    /**
     * Informacje wymagane do zaszyfrowania wyniku zapytania.
     *
     * @var PostApiV2InvoicesExportsEncryption $encryption
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('encryption')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2InvoicesExportsEncryption')]
    public PostApiV2InvoicesExportsEncryption $encryption;

    /**
     * Zestaw filtrów do wyszukiwania faktur.
     *
     * @var Filters $filters
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('filters')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\Filters')]
    public Filters $filters;

    /**
     * @param  PostApiV2InvoicesExportsEncryption  $encryption
     * @param  Filters  $filters
     * @phpstan-pure
     */
    public function __construct(PostApiV2InvoicesExportsEncryption $encryption, Filters $filters)
    {
        $this->encryption = $encryption;
        $this->filters = $filters;
    }
}