<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
class PostApiV2PermissionsQueryPersonsGrantsRequestBody
{
    /**
     * Typ zapytania.
     *
     * | Type | Value |
     * | --- | --- |
     * | PermissionsInCurrentContext | Uprawnienia posiadane w aktualnym kontekście |
     * | PermissionsGrantedInCurrentContext | Uprawnienia nadane w aktualnym kontekście |
     *
     * @var Components\PersonPermissionsQueryType $queryType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('queryType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\PersonPermissionsQueryType')]
    public Components\PersonPermissionsQueryType $queryType;

    /**
     * Identyfikator osoby lub podmiotu nadającego uprawnienie.
     *
     * | Type | Value |
     * | --- | --- |
     * | Nip | 10 cyfrowy numer NIP |
     * | Pesel | 11 cyfrowy numer PESEL |
     * | Fingerprint | Odcisk palca certyfikatu |
     * | System | Identyfikator systemowy KSeF |
     *
     * @var ?AuthorIdentifier $authorIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\AuthorIdentifier|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AuthorIdentifier $authorIdentifier = null;

    /**
     * Identyfikator osoby lub podmiotu uprawnionego.
     *
     * | Type | Value |
     * | --- | --- |
     * | Nip | 10 cyfrowy numer NIP |
     * | Pesel | 11 cyfrowy numer PESEL |
     * | Fingerprint | Odcisk palca certyfikatu |
     *
     * @var ?PostApiV2PermissionsQueryPersonsGrantsAuthorizedIdentifier $authorizedIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorizedIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2PermissionsQueryPersonsGrantsAuthorizedIdentifier|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostApiV2PermissionsQueryPersonsGrantsAuthorizedIdentifier $authorizedIdentifier = null;

    /**
     * Identyfikator podmiotu docelowego (dla uprawnień pośrednich).
     *
     * | Type | Value |
     * | --- | --- |
     * | Nip | 10 cyfrowy numer NIP |
     * | AllPartners | Identyfikator oznaczający, że uprawnienie nadane w sposób pośredni jest typu generalnego |
     *
     * @var ?PostApiV2PermissionsQueryPersonsGrantsTargetIdentifier $targetIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('targetIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2PermissionsQueryPersonsGrantsTargetIdentifier|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostApiV2PermissionsQueryPersonsGrantsTargetIdentifier $targetIdentifier = null;

    /**
     * Możliwe uprawnienia do filtrowania.
     *
     * @var ?array<Components\PersonPermissionType> $permissionTypes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permissionTypes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\PersonPermissionType>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $permissionTypes = null;

    /**
     * Stan uprawnienia. 
     *
     * | Type | Value |
     * | --- | --- |
     * | Active | Uprawnienia aktywne |
     * | Inactive | Uprawnienia nieaktywne, nadane w sposób poœredni |
     *
     * @var ?PermissionState $permissionState
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permissionState')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PermissionState|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PermissionState $permissionState = null;

    /**
     * @param  Components\PersonPermissionsQueryType  $queryType
     * @param  ?AuthorIdentifier  $authorIdentifier
     * @param  ?PostApiV2PermissionsQueryPersonsGrantsAuthorizedIdentifier  $authorizedIdentifier
     * @param  ?PostApiV2PermissionsQueryPersonsGrantsTargetIdentifier  $targetIdentifier
     * @param  ?array<Components\PersonPermissionType>  $permissionTypes
     * @param  ?PermissionState  $permissionState
     * @phpstan-pure
     */
    public function __construct(Components\PersonPermissionsQueryType $queryType, ?AuthorIdentifier $authorIdentifier = null, ?PostApiV2PermissionsQueryPersonsGrantsAuthorizedIdentifier $authorizedIdentifier = null, ?PostApiV2PermissionsQueryPersonsGrantsTargetIdentifier $targetIdentifier = null, ?array $permissionTypes = null, ?PermissionState $permissionState = null)
    {
        $this->queryType = $queryType;
        $this->authorIdentifier = $authorIdentifier;
        $this->authorizedIdentifier = $authorizedIdentifier;
        $this->targetIdentifier = $targetIdentifier;
        $this->permissionTypes = $permissionTypes;
        $this->permissionState = $permissionState;
    }
}