<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
class PostApiV2PermissionsEntitiesGrantsRequest
{
    /**
     * Identyfikator podmiotu.
     *
     * | Type | Value |
     * | --- | --- |
     * | Nip | 10 cyfrowy numer NIP |
     *
     * @var PostApiV2PermissionsEntitiesGrantsSubjectIdentifier $subjectIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subjectIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2PermissionsEntitiesGrantsSubjectIdentifier')]
    public PostApiV2PermissionsEntitiesGrantsSubjectIdentifier $subjectIdentifier;

    /**
     * Lista nadawanych uprawnień. Każda wartość może wystąpić tylko raz.
     *
     * @var array<Components\EntityPermission> $permissions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permissions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\EntityPermission>')]
    public array $permissions;

    /**
     * Opis nadawanych uprawnień.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * @param  PostApiV2PermissionsEntitiesGrantsSubjectIdentifier  $subjectIdentifier
     * @param  array<Components\EntityPermission>  $permissions
     * @param  string  $description
     * @phpstan-pure
     */
    public function __construct(PostApiV2PermissionsEntitiesGrantsSubjectIdentifier $subjectIdentifier, array $permissions, string $description)
    {
        $this->subjectIdentifier = $subjectIdentifier;
        $this->permissions = $permissions;
        $this->description = $description;
    }
}