<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
class PostApiV2PermissionsPersonsGrantsRequest
{
    /**
     * Identyfikator osoby fizycznej.
     *
     * | Type | Value |
     * | --- | --- |
     * | Nip | 10 cyfrowy numer NIP |
     * | Pesel | 11 cyfrowy numer PESEL |
     * | Fingerprint | Odcisk palca certyfikatu |
     *
     * @var PostApiV2PermissionsPersonsGrantsSubjectIdentifier $subjectIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subjectIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2PermissionsPersonsGrantsSubjectIdentifier')]
    public PostApiV2PermissionsPersonsGrantsSubjectIdentifier $subjectIdentifier;

    /**
     * Lista nadawanych uprawnień. Każda wartość może wystąpić tylko raz.
     *
     * @var array<Components\PersonPermissionType> $permissions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permissions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\PersonPermissionType>')]
    public array $permissions;

    /**
     * Opis nadawanych uprawnień.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * @param  PostApiV2PermissionsPersonsGrantsSubjectIdentifier  $subjectIdentifier
     * @param  array<Components\PersonPermissionType>  $permissions
     * @param  string  $description
     * @phpstan-pure
     */
    public function __construct(PostApiV2PermissionsPersonsGrantsSubjectIdentifier $subjectIdentifier, array $permissions, string $description)
    {
        $this->subjectIdentifier = $subjectIdentifier;
        $this->permissions = $permissions;
        $this->description = $description;
    }
}