<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
/**
 * PostApiV2PermissionsIndirectGrantsTargetIdentifier - Identyfikator podmiotu, w którego kontekście chcemy pośrednio nadać uprawnienia. W przypadku nadawania uprawnienia generalnego, pole to powinno mieć wartość null.
 *
 * | Type | Value |
 * | --- | --- |
 * | Nip | 10 cyfrowy numer NIP |
 * | AllPartners | Identyfikator oznaczający, że uprawnienie nadane w sposób pośredni jest typu generalnego |
 */
class PostApiV2PermissionsIndirectGrantsTargetIdentifier
{
    /**
     * Typ identyfikatora.
     *
     * @var Components\IndirectPermissionsTargetIdentifierType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\IndirectPermissionsTargetIdentifierType')]
    public Components\IndirectPermissionsTargetIdentifierType $type;

    /**
     * Wartość identyfikatora. W przypadku typu AllPartners należy pozostawić puste. W pozostałych przypadkach pole jest wymagane.
     *
     * @var ?string $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $value = null;

    /**
     * @param  Components\IndirectPermissionsTargetIdentifierType  $type
     * @param  ?string  $value
     * @phpstan-pure
     */
    public function __construct(Components\IndirectPermissionsTargetIdentifierType $type, ?string $value = null)
    {
        $this->type = $type;
        $this->value = $value;
    }
}