<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


/** PostApiV2InvoicesQueryMetadataBuyer - Dane nabywcy. */
class PostApiV2InvoicesQueryMetadataBuyer
{
    /**
     * Typ identyfikatora nabywcy.
     *
     * | Wartość | Opis |
     * | --- | --- |
     * | None | Brak identyfikatora nabywcy |
     * | Other | Inny |
     * | Nip | NIP |
     * | VatUe | VAT UE |
     *
     *
     * @var ?PostApiV2InvoicesQueryMetadataIdentifierType $identifierType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifierType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2InvoicesQueryMetadataIdentifierType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostApiV2InvoicesQueryMetadataIdentifierType $identifierType = null;

    /**
     * Wartość identyfikatora nabywcy.
     *
     * @var ?string $identifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $identifier = null;

    /**
     * @param  ?PostApiV2InvoicesQueryMetadataIdentifierType  $identifierType
     * @param  ?string  $identifier
     * @phpstan-pure
     */
    public function __construct(?PostApiV2InvoicesQueryMetadataIdentifierType $identifierType = null, ?string $identifier = null)
    {
        $this->identifierType = $identifierType;
        $this->identifier = $identifier;
    }
}