<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


/** PostApiV2InvoicesQueryMetadataAmount - Filtr kwotowy – brutto, netto lub VAT (z wartością). */
class PostApiV2InvoicesQueryMetadataAmount
{
    /**
     *
     * @var ?PostApiV2InvoicesQueryMetadataType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2InvoicesQueryMetadataType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostApiV2InvoicesQueryMetadataType $type = null;

    /**
     *
     * @var ?float $from
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $from = null;

    /**
     *
     * @var ?float $to
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('to')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $to = null;

    /**
     * @param  ?PostApiV2InvoicesQueryMetadataType  $type
     * @param  ?float  $from
     * @param  ?float  $to
     * @phpstan-pure
     */
    public function __construct(?PostApiV2InvoicesQueryMetadataType $type = null, ?float $from = null, ?float $to = null)
    {
        $this->type = $type;
        $this->from = $from;
        $this->to = $to;
    }
}