<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
class PostApiV2PermissionsQueryAuthorizationsGrantsRequestBody
{
    /**
     * Typ zapytania.
     *
     * | Type | Value |
     * | --- | --- |
     * | Granted | Uprawnienia nadane innym podmiotom |
     * | Received | Uprawnienia otrzymane od innych podmiotów |
     *
     * @var Components\QueryType $queryType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('queryType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\QueryType')]
    public Components\QueryType $queryType;

    /**
     * Identyfikator podmiotu uprawniającego.
     *
     * | Type | Value |
     * | --- | --- |
     * | Nip | 10 cyfrowy numer NIP |
     *
     * @var ?AuthorizingIdentifier $authorizingIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorizingIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\AuthorizingIdentifier|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AuthorizingIdentifier $authorizingIdentifier = null;

    /**
     * Identyfikator podmiotu uprawnionego.
     *
     * | Type | Value |
     * | --- | --- |
     * | Nip | 10 cyfrowy numer NIP |
     * | PeppolId | Identyfikator dostawcy usług Peppol |
     *
     * @var ?PostApiV2PermissionsQueryAuthorizationsGrantsAuthorizedIdentifier $authorizedIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorizedIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2PermissionsQueryAuthorizationsGrantsAuthorizedIdentifier|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostApiV2PermissionsQueryAuthorizationsGrantsAuthorizedIdentifier $authorizedIdentifier = null;

    /**
     * Możliwe uprawnienia do filtrowania.
     *
     * @var ?array<Components\InvoicePermissionType> $permissionTypes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permissionTypes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\InvoicePermissionType>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $permissionTypes = null;

    /**
     * @param  Components\QueryType  $queryType
     * @param  ?AuthorizingIdentifier  $authorizingIdentifier
     * @param  ?PostApiV2PermissionsQueryAuthorizationsGrantsAuthorizedIdentifier  $authorizedIdentifier
     * @param  ?array<Components\InvoicePermissionType>  $permissionTypes
     * @phpstan-pure
     */
    public function __construct(Components\QueryType $queryType, ?AuthorizingIdentifier $authorizingIdentifier = null, ?PostApiV2PermissionsQueryAuthorizationsGrantsAuthorizedIdentifier $authorizedIdentifier = null, ?array $permissionTypes = null)
    {
        $this->queryType = $queryType;
        $this->authorizingIdentifier = $authorizingIdentifier;
        $this->authorizedIdentifier = $authorizedIdentifier;
        $this->permissionTypes = $permissionTypes;
    }
}