<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Utils\SpeakeasyMetadata;
class PostApiV2PermissionsQueryPersonsGrantsRequest
{
    /**
     * Numer strony wyników.
     *
     * @var ?int $pageOffset
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=pageOffset')]
    public ?int $pageOffset = null;

    /**
     * Rozmiar strony wyników.
     *
     * @var ?int $pageSize
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=pageSize')]
    public ?int $pageSize = null;

    /**
     *
     * @var ?PostApiV2PermissionsQueryPersonsGrantsRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?PostApiV2PermissionsQueryPersonsGrantsRequestBody $requestBody = null;

    /**
     * @param  ?int  $pageOffset
     * @param  ?int  $pageSize
     * @param  ?PostApiV2PermissionsQueryPersonsGrantsRequestBody  $requestBody
     * @phpstan-pure
     */
    public function __construct(?int $pageOffset = null, ?int $pageSize = null, ?PostApiV2PermissionsQueryPersonsGrantsRequestBody $requestBody = null)
    {
        $this->pageOffset = $pageOffset;
        $this->pageSize = $pageSize;
        $this->requestBody = $requestBody;
    }
}