<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


/** PostApiV2InvoicesQueryMetadataSeller - Dane sprzedawcy. */
class PostApiV2InvoicesQueryMetadataSeller
{
    /**
     * Identyfikator sprzedawcy.
     *
     * @var ?string $identifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $identifier = null;

    /**
     * @param  ?string  $identifier
     * @phpstan-pure
     */
    public function __construct(?string $identifier = null)
    {
        $this->identifier = $identifier;
    }
}