<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


/** PostApiV2InvoicesQueryMetadataSeller - Dane sprzedawcy. */
class PostApiV2InvoicesQueryMetadataSeller
{
    /**
     * Identyfikator sprzedawcy.
     *
     * @var ?string $identifier
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $identifier = null;

    /**
     * Nip sprzedawcy.
     *
     * @var ?string $nip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nip')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $nip = null;

    /**
     * @param  ?string  $identifier
     * @param  ?string  $nip
     * @phpstan-pure
     */
    public function __construct(?string $identifier = null, ?string $nip = null)
    {
        $this->identifier = $identifier;
        $this->nip = $nip;
    }
}