<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
class PostApiV2PermissionsAuthorizationsGrantsRequest
{
    /**
     * Identyfikator podmiotu.
     *
     * | Type | Value |
     * | --- | --- |
     * | Nip | 10 cyfrowy numer NIP |
     *
     * @var PostApiV2PermissionsAuthorizationsGrantsSubjectIdentifier $subjectIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subjectIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2PermissionsAuthorizationsGrantsSubjectIdentifier')]
    public PostApiV2PermissionsAuthorizationsGrantsSubjectIdentifier $subjectIdentifier;

    /**
     * Nadawane uprawnienie o charakterze upoważnienia.
     *
     * @var Components\EntityAuthorizationPermissionType $permission
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permission')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\EntityAuthorizationPermissionType')]
    public Components\EntityAuthorizationPermissionType $permission;

    /**
     * Opis nadawanego uprawnienia.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * @param  PostApiV2PermissionsAuthorizationsGrantsSubjectIdentifier  $subjectIdentifier
     * @param  Components\EntityAuthorizationPermissionType  $permission
     * @param  string  $description
     * @phpstan-pure
     */
    public function __construct(PostApiV2PermissionsAuthorizationsGrantsSubjectIdentifier $subjectIdentifier, Components\EntityAuthorizationPermissionType $permission, string $description)
    {
        $this->subjectIdentifier = $subjectIdentifier;
        $this->permission = $permission;
        $this->description = $description;
    }
}