<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
class PostApiV2PermissionsIndirectGrantsRequest
{
    /**
     * Identyfikator osoby fizycznej.
     *
     * | Type | Value |
     * | --- | --- |
     * | Nip | 10 cyfrowy numer NIP |
     * | Pesel | 11 cyfrowy numer PESEL |
     * | Fingerprint | Odcisk palca certyfikatu |
     *
     * @var PostApiV2PermissionsIndirectGrantsSubjectIdentifier $subjectIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subjectIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2PermissionsIndirectGrantsSubjectIdentifier')]
    public PostApiV2PermissionsIndirectGrantsSubjectIdentifier $subjectIdentifier;

    /**
     * Lista nadawanych uprawnień. Każda wartość może wystąpić tylko raz.
     *
     * @var array<Components\IndirectPermissionType> $permissions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permissions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\IndirectPermissionType>')]
    public array $permissions;

    /**
     * Opis nadawanych uprawnień.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * Identyfikator podmiotu, w którego kontekście chcemy pośrednio nadać uprawnienia. W przypadku nadawania uprawnienia generalnego, pole to powinno mieć wartość null.
     *
     * | Type | Value |
     * | --- | --- |
     * | Nip | 10 cyfrowy numer NIP |
     * | AllPartners | Identyfikator oznaczający, że uprawnienie nadane w sposób pośredni jest typu generalnego |
     *
     * @var ?PostApiV2PermissionsIndirectGrantsTargetIdentifier $targetIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('targetIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2PermissionsIndirectGrantsTargetIdentifier|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PostApiV2PermissionsIndirectGrantsTargetIdentifier $targetIdentifier = null;

    /**
     * @param  PostApiV2PermissionsIndirectGrantsSubjectIdentifier  $subjectIdentifier
     * @param  array<Components\IndirectPermissionType>  $permissions
     * @param  string  $description
     * @param  ?PostApiV2PermissionsIndirectGrantsTargetIdentifier  $targetIdentifier
     * @phpstan-pure
     */
    public function __construct(PostApiV2PermissionsIndirectGrantsSubjectIdentifier $subjectIdentifier, array $permissions, string $description, ?PostApiV2PermissionsIndirectGrantsTargetIdentifier $targetIdentifier = null)
    {
        $this->subjectIdentifier = $subjectIdentifier;
        $this->permissions = $permissions;
        $this->description = $description;
        $this->targetIdentifier = $targetIdentifier;
    }
}