<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
/** PostApiV2AuthKsefTokenContextIdentifier - Indentyfikator kontekstu do którego następuje uwierzytelnienie. */
class PostApiV2AuthKsefTokenContextIdentifier
{
    /**
     * Typ identyfikatora
     *
     * @var Components\ContextIdentifierType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\ContextIdentifierType')]
    public Components\ContextIdentifierType $type;

    /**
     * Wartość identyfikatora
     *
     * @var string $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    public string $value;

    /**
     * @param  Components\ContextIdentifierType  $type
     * @param  string  $value
     * @phpstan-pure
     */
    public function __construct(Components\ContextIdentifierType $type, string $value)
    {
        $this->type = $type;
        $this->value = $value;
    }
}