<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
/**
 * PostApiV2PermissionsQueryPersonsGrantsTargetIdentifier - Identyfikator podmiotu docelowego (dla uprawnień pośrednich).
 *
 * | Type | Value |
 * | --- | --- |
 * | Nip | 10 cyfrowy numer NIP |
 */
class PostApiV2PermissionsQueryPersonsGrantsTargetIdentifier
{
    /**
     * Typ identyfikatora.
     *
     * @var Components\PersonPermissionsTargetIdentifierType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\PersonPermissionsTargetIdentifierType')]
    public Components\PersonPermissionsTargetIdentifierType $type;

    /**
     * Wartość identyfikatora.
     *
     * @var string $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    public string $value;

    /**
     * @param  Components\PersonPermissionsTargetIdentifierType  $type
     * @param  string  $value
     * @phpstan-pure
     */
    public function __construct(Components\PersonPermissionsTargetIdentifierType $type, string $value)
    {
        $this->type = $type;
        $this->value = $value;
    }
}