<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


class PostApiV2SessionsBatchRequest
{
    /**
     * Schemat faktur wysyłanych w ramach sesji.
     *
     *
     * Obsługiwane schematy:
     * | SystemCode | SchemaVersion | Value |
     * | --- | --- | --- |
     * | FA (2) | 1-0E | FA |
     * | FA (3) | 1-0E | FA |
     *
     *
     * @var PostApiV2SessionsBatchFormCode $formCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('formCode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2SessionsBatchFormCode')]
    public PostApiV2SessionsBatchFormCode $formCode;

    /**
     * Informacje o przesyłanej paczce faktur.
     *
     * @var BatchFile $batchFile
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('batchFile')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\BatchFile')]
    public BatchFile $batchFile;

    /**
     * Symetryczny klucz szyfrujący plik paczki, zaszyfrowany kluczem publicznym Ministerstwa Finansów.
     *
     * @var PostApiV2SessionsBatchEncryption $encryption
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('encryption')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2SessionsBatchEncryption')]
    public PostApiV2SessionsBatchEncryption $encryption;

    /**
     * Określa, czy podatnik deklaruje tryb fakurowania "offline" dla dokumentów przesyłanych w sesji wsadowej.
     *
     * @var ?bool $offlineMode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('offlineMode')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $offlineMode = null;

    /**
     * @param  PostApiV2SessionsBatchFormCode  $formCode
     * @param  BatchFile  $batchFile
     * @param  PostApiV2SessionsBatchEncryption  $encryption
     * @param  ?bool  $offlineMode
     * @phpstan-pure
     */
    public function __construct(PostApiV2SessionsBatchFormCode $formCode, BatchFile $batchFile, PostApiV2SessionsBatchEncryption $encryption, ?bool $offlineMode = false)
    {
        $this->formCode = $formCode;
        $this->batchFile = $batchFile;
        $this->encryption = $encryption;
        $this->offlineMode = $offlineMode;
    }
}