<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


/** PostApiV2SessionsBatchEncryption - Symetryczny klucz szyfrujący plik paczki, zaszyfrowany kluczem publicznym Ministerstwa Finansów. */
class PostApiV2SessionsBatchEncryption
{
    /**
     * Klucz symetryczny zaszyfrowany algorytmem RSA (Padding: OAEP z SHA-256), zakodowany w formacie Base64.
     *
     *
     * [Klucz publiczny RSA](/public-keys/publicKey.pem)
     *
     * @var string $encryptedSymmetricKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('encryptedSymmetricKey')]
    public string $encryptedSymmetricKey;

    /**
     * Wektor inicjalizujący (IV) używany do szyfrowania symetrycznego, zakodowany w formacie Base64.
     *
     * @var string $initializationVector
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('initializationVector')]
    public string $initializationVector;

    /**
     * @param  string  $encryptedSymmetricKey
     * @param  string  $initializationVector
     * @phpstan-pure
     */
    public function __construct(string $encryptedSymmetricKey, string $initializationVector)
    {
        $this->encryptedSymmetricKey = $encryptedSymmetricKey;
        $this->initializationVector = $initializationVector;
    }
}