<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


class PostApiV2AuthKsefTokenRequest
{
    /**
     * Wygenerowany wcześniej challenge.
     *
     * @var string $challenge
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('challenge')]
    public string $challenge;

    /**
     * Indentyfikator kontekstu do którego następuje uwierzytelnienie.
     *
     * @var PostApiV2AuthKsefTokenContextIdentifier $contextIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contextIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\PostApiV2AuthKsefTokenContextIdentifier')]
    public PostApiV2AuthKsefTokenContextIdentifier $contextIdentifier;

    /**
     * Zaszyfrowany token wraz z timestampem z challenge'a, w formacie `token|timestamp`.
     *
     * @var string $encryptedToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('encryptedToken')]
    public string $encryptedToken;

    /**
     * Reguła walidacji adresu IP klienta przy każdym użyciu tokena dostępu.
     *
     * @var ?IpAddressPolicy $ipAddressPolicy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ipAddressPolicy')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\IpAddressPolicy|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?IpAddressPolicy $ipAddressPolicy = null;

    /**
     * @param  string  $challenge
     * @param  PostApiV2AuthKsefTokenContextIdentifier  $contextIdentifier
     * @param  string  $encryptedToken
     * @param  ?IpAddressPolicy  $ipAddressPolicy
     * @phpstan-pure
     */
    public function __construct(string $challenge, PostApiV2AuthKsefTokenContextIdentifier $contextIdentifier, string $encryptedToken, ?IpAddressPolicy $ipAddressPolicy = null)
    {
        $this->challenge = $challenge;
        $this->contextIdentifier = $contextIdentifier;
        $this->encryptedToken = $encryptedToken;
        $this->ipAddressPolicy = $ipAddressPolicy;
    }
}