<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;

use Intermedia\Ksef\Apiv2\Models\Components;
class RevokeTestPermissionsAuthorizedIdentifier
{
    /**
     *
     * @var Components\TestDataAuthorizedIdentifierType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\TestDataAuthorizedIdentifierType')]
    public Components\TestDataAuthorizedIdentifierType $type;

    /**
     *
     * @var string $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    public string $value;

    /**
     * @param  Components\TestDataAuthorizedIdentifierType  $type
     * @param  string  $value
     * @phpstan-pure
     */
    public function __construct(Components\TestDataAuthorizedIdentifierType $type, string $value)
    {
        $this->type = $type;
        $this->value = $value;
    }
}