<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


class RevokeTestPermissionsRequest
{
    /**
     *
     * @var RevokeTestPermissionsContextIdentifier $contextIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contextIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\RevokeTestPermissionsContextIdentifier')]
    public RevokeTestPermissionsContextIdentifier $contextIdentifier;

    /**
     *
     * @var RevokeTestPermissionsAuthorizedIdentifier $authorizedIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorizedIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\RevokeTestPermissionsAuthorizedIdentifier')]
    public RevokeTestPermissionsAuthorizedIdentifier $authorizedIdentifier;

    /**
     * @param  RevokeTestPermissionsContextIdentifier  $contextIdentifier
     * @param  RevokeTestPermissionsAuthorizedIdentifier  $authorizedIdentifier
     * @phpstan-pure
     */
    public function __construct(RevokeTestPermissionsContextIdentifier $contextIdentifier, RevokeTestPermissionsAuthorizedIdentifier $authorizedIdentifier)
    {
        $this->contextIdentifier = $contextIdentifier;
        $this->authorizedIdentifier = $authorizedIdentifier;
    }
}