<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


/**
 *
 * @deprecated  enum: This will be removed in a future release, please migrate away from it as soon as possible.
 */
enum SchemaType: string
{
    case Fa1 = 'FA1';
    case Fa2 = 'FA2';
    case Fa3 = 'FA3';
}
