<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Operations;


class UpdateContextSessionLimitsRequest
{
    /**
     * Limity dla sesji interaktywnych.
     *
     * @var OnlineSession $onlineSession
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('onlineSession')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\OnlineSession')]
    public OnlineSession $onlineSession;

    /**
     * Limity dla sesji wsadowych.
     *
     * @var BatchSession $batchSession
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('batchSession')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Operations\BatchSession')]
    public BatchSession $batchSession;

    /**
     * @param  OnlineSession  $onlineSession
     * @param  BatchSession  $batchSession
     * @phpstan-pure
     */
    public function __construct(OnlineSession $onlineSession, BatchSession $batchSession)
    {
        $this->onlineSession = $onlineSession;
        $this->batchSession = $batchSession;
    }
}