<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class AttachmentPermissionGrantRequest
{
    /**
     *
     * @var ?string $nip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nip')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $nip = null;

    /**
     * @param  ?string  $nip
     * @phpstan-pure
     */
    public function __construct(?string $nip = null)
    {
        $this->nip = $nip;
    }
}