<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


/** AuthorizedSubject - Podmiot upoważniony. */
class AuthorizedSubject
{
    /**
     * Nip podmiotu upoważnionego
     *
     * @var string $nip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nip')]
    public string $nip;

    /**
     * Rola podmiotu upoważnionego.
     *
     * @var int $role
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('role')]
    public int $role;

    /**
     * Nazwa podmiotu upoważnionego.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * @param  string  $nip
     * @param  int  $role
     * @param  ?string  $name
     * @phpstan-pure
     */
    public function __construct(string $nip, int $role, ?string $name = null)
    {
        $this->nip = $nip;
        $this->role = $role;
        $this->name = $name;
    }
}