<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


/** Typ identyfikatora podmiotu uprawnionego. */
enum AuthorizedIdentifierType: string
{
    case Nip = 'Nip';
    case Pesel = 'Pesel';
    case Fingerprint = 'Fingerprint';
}
