<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class AuthenticationInitResponse
{
    /**
     * Numer referencyjny operacji uwierzytelnienia.
     *
     * @var string $referenceNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('referenceNumber')]
    public string $referenceNumber;

    /**
     * Token operacji uwierzytelnienia.
     *
     * @var AuthenticationInitResponseAuthenticationToken $authenticationToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authenticationToken')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\AuthenticationInitResponseAuthenticationToken')]
    public AuthenticationInitResponseAuthenticationToken $authenticationToken;

    /**
     * @param  string  $referenceNumber
     * @param  AuthenticationInitResponseAuthenticationToken  $authenticationToken
     * @phpstan-pure
     */
    public function __construct(string $referenceNumber, AuthenticationInitResponseAuthenticationToken $authenticationToken)
    {
        $this->referenceNumber = $referenceNumber;
        $this->authenticationToken = $authenticationToken;
    }
}