<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


/** AuthenticationTokenContextIdentifier - Identyfikator kontekstu, w którym został wygenerowany token i do którego daje dostęp. */
class AuthenticationTokenContextIdentifier
{
    /**
     * Typ identyfikatora
     *
     * @var ContextIdentifierType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\ContextIdentifierType')]
    public ContextIdentifierType $type;

    /**
     * Wartość identyfikatora
     *
     * @var string $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    public string $value;

    /**
     * @param  ContextIdentifierType  $type
     * @param  string  $value
     * @phpstan-pure
     */
    public function __construct(ContextIdentifierType $type, string $value)
    {
        $this->type = $type;
        $this->value = $value;
    }
}