<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class AuthenticationChallengeResponse
{
    /**
     * Unikalny challenge.
     *
     * @var string $challenge
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('challenge')]
    public string $challenge;

    /**
     * Czas wygenerowania challenge-a.
     *
     * @var \DateTime $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    public \DateTime $timestamp;

    /**
     * @param  string  $challenge
     * @param  \DateTime  $timestamp
     * @phpstan-pure
     */
    public function __construct(string $challenge, \DateTime $timestamp)
    {
        $this->challenge = $challenge;
        $this->timestamp = $timestamp;
    }
}