<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


/** AuthorIdentifier - Identyfikator osoby która wygenerowała token. */
class AuthorIdentifier
{
    /**
     *
     * @var ?SubjectIdentifierType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\SubjectIdentifierType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SubjectIdentifierType $type = null;

    /**
     *
     * @var ?string $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $value = null;

    /**
     * @param  ?SubjectIdentifierType  $type
     * @param  ?string  $value
     * @phpstan-pure
     */
    public function __construct(?SubjectIdentifierType $type = null, ?string $value = null)
    {
        $this->type = $type;
        $this->value = $value;
    }
}