<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


/** AuthorizedSubject - [Mock] Podmiot upoważniony. */
class AuthorizedSubject
{
    /**
     * Rola podmiotu upoważnionego
     *
     * @var ?int $role
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('role')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $role = null;

    /**
     * Identyfikator podmiotu upoważnionego
     *
     * @var ?string $identifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $identifier = null;

    /**
     * Nazwa podmiotu upoważnionego
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * @param  ?int  $role
     * @param  ?string  $identifier
     * @param  ?string  $name
     * @phpstan-pure
     */
    public function __construct(?int $role = null, ?string $identifier = null, ?string $name = null)
    {
        $this->role = $role;
        $this->identifier = $identifier;
        $this->name = $name;
    }
}