<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class BatchFilePartInfo
{
    /**
     * Numer sekwencyjny części pliku paczki.
     *
     * @var int $ordinalNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ordinalNumber')]
    public int $ordinalNumber;

    /**
     * Rozmiar zaszyfrowanej części pliku paczki w bajtach.
     *
     * @var int $fileSize
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fileSize')]
    public int $fileSize;

    /**
     * Skrót SHA256 zaszyfrowanej części pliku paczki, zakodowany w formacie Base64.
     *
     * @var string $fileHash
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fileHash')]
    public string $fileHash;

    /**
     * Nazwa części pliku paczki.
     *
     * @var ?string $fileName
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fileName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $fileName = null;

    /**
     * @param  int  $ordinalNumber
     * @param  int  $fileSize
     * @param  string  $fileHash
     * @param  ?string  $fileName
     * @phpstan-pure
     */
    public function __construct(int $ordinalNumber, int $fileSize, string $fileHash, ?string $fileName = null)
    {
        $this->ordinalNumber = $ordinalNumber;
        $this->fileSize = $fileSize;
        $this->fileHash = $fileHash;
        $this->fileName = $fileName;
    }
}