<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


/**
 * | Wartość | Opis |
 *
 * | --- | --- |
 * | None | Brak identyfikatora nabywcy |
 * | Other | Inny identyfikator |
 * | Nip | 10 cyfrowy numer NIP |
 * | VatUe | Identyfikator VAT UE podmiotu unijnego |
 *
 */
enum BuyerIdentifierType: string
{
    case None = 'None';
    case Other = 'Other';
    case Nip = 'Nip';
    case VatUe = 'VatUe';
}
