<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


/** Buyer - Dane identyfikujące nabywcę. */
class Buyer
{
    /**
     * Typ identyfikatora nabywcy.
     *
     * | Wartość | Opis |
     * | --- | --- |
     * | None | Brak identyfikatora nabywcy |
     * | Other | Inny |
     * | Nip | NIP |
     * | VatUe | VAT UE |
     *
     *
     * @var BuyerIdentifierType $identifierType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifierType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\BuyerIdentifierType')]
    public BuyerIdentifierType $identifierType;

    /**
     * Wartośc identyfikatora nabywcy.
     *
     * @var ?string $identifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $identifier = null;

    /**
     * Nazwa nabywcy.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * @param  BuyerIdentifierType  $identifierType
     * @param  ?string  $identifier
     * @param  ?string  $name
     * @phpstan-pure
     */
    public function __construct(BuyerIdentifierType $identifierType, ?string $identifier = null, ?string $name = null)
    {
        $this->identifierType = $identifierType;
        $this->identifier = $identifier;
        $this->name = $name;
    }
}