<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


/** CertificateLimitsResponse - Informacje o limitach wniosków oraz certyfikatów dla uwierzytelnionego podmiotu. */
class CertificateLimitsResponse
{
    /**
     * Flaga informująca czy uwierzytelniony podmiot może złożyć nowy wniosek o certyfikat.
     *
     * @var bool $canRequest
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('canRequest')]
    public bool $canRequest;

    /**
     * Informacje o limitach związanych z liczbą możliwych do złożenia wniosków certyfikacyjnych.
     *
     * @var Enrollment $enrollment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enrollment')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\Enrollment')]
    public Enrollment $enrollment;

    /**
     * Informacje o limitach dotyczących liczby aktywnych certyfikatów wydanych dla danego podmiotu.
     *
     * @var Certificate $certificate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('certificate')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\Certificate')]
    public Certificate $certificate;

    /**
     * @param  bool  $canRequest
     * @param  Enrollment  $enrollment
     * @param  Certificate  $certificate
     * @phpstan-pure
     */
    public function __construct(bool $canRequest, Enrollment $enrollment, Certificate $certificate)
    {
        $this->canRequest = $canRequest;
        $this->enrollment = $enrollment;
        $this->certificate = $certificate;
    }
}