<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class EntityRole
{
    /**
     * Rola.
     *
     * @var EntityRoleType $role
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('role')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\EntityRoleType')]
    public EntityRoleType $role;

    /**
     * Opis.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * Data rozpoczęcia obowiązywania roli.
     *
     * @var \DateTime $startDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('startDate')]
    public \DateTime $startDate;

    /**
     * Identyfikator podmiotu nadrzędnego.
     *
     * @var ?string $parentEntityIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parentEntityIdentifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $parentEntityIdentifier = null;

    /**
     * Typ identyfikatora podmiotu nadrzędnego.
     *
     * @var ?ParentEntityIdentifierType $parentEntityIdentifierType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parentEntityIdentifierType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\ParentEntityIdentifierType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?ParentEntityIdentifierType $parentEntityIdentifierType = null;

    /**
     * @param  EntityRoleType  $role
     * @param  string  $description
     * @param  \DateTime  $startDate
     * @param  ?string  $parentEntityIdentifier
     * @param  ?ParentEntityIdentifierType  $parentEntityIdentifierType
     * @phpstan-pure
     */
    public function __construct(EntityRoleType $role, string $description, \DateTime $startDate, ?string $parentEntityIdentifier = null, ?ParentEntityIdentifierType $parentEntityIdentifierType = null)
    {
        $this->role = $role;
        $this->description = $description;
        $this->startDate = $startDate;
        $this->parentEntityIdentifier = $parentEntityIdentifier;
        $this->parentEntityIdentifierType = $parentEntityIdentifierType;
    }
}