<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class EuEntityPermission
{
    /**
     * Identyfikator uprawnienia.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Identyfikator uprawniającego.
     *
     * @var string $authorIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorIdentifier')]
    public string $authorIdentifier;

    /**
     * Typ identyfikatora uprawniającego.
     *
     * @var EuEntityPermissionsAuthorIdentifierType $authorIdentifierType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorIdentifierType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\EuEntityPermissionsAuthorIdentifierType')]
    public EuEntityPermissionsAuthorIdentifierType $authorIdentifierType;

    /**
     * Identyfikator podmiotu unijnego.
     *
     * @var string $vatUeIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('vatUeIdentifier')]
    public string $vatUeIdentifier;

    /**
     * Nazwa podmiotu unijnego.
     *
     * @var string $euEntityName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('euEntityName')]
    public string $euEntityName;

    /**
     * Uprawniony odcisk palca certyfikatu.
     *
     * @var string $authorizedFingerprintIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorizedFingerprintIdentifier')]
    public string $authorizedFingerprintIdentifier;

    /**
     * Uprawnienie.
     *
     * @var EuEntityPermissionsQueryPermissionType $permissionScope
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permissionScope')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\EuEntityPermissionsQueryPermissionType')]
    public EuEntityPermissionsQueryPermissionType $permissionScope;

    /**
     * Opis uprawnienia.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * Data rozpoczęcia obowiązywania uprawnienia.
     *
     * @var \DateTime $startDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('startDate')]
    public \DateTime $startDate;

    /**
     * @param  string  $id
     * @param  string  $authorIdentifier
     * @param  EuEntityPermissionsAuthorIdentifierType  $authorIdentifierType
     * @param  string  $vatUeIdentifier
     * @param  string  $euEntityName
     * @param  string  $authorizedFingerprintIdentifier
     * @param  EuEntityPermissionsQueryPermissionType  $permissionScope
     * @param  string  $description
     * @param  \DateTime  $startDate
     * @phpstan-pure
     */
    public function __construct(string $id, string $authorIdentifier, EuEntityPermissionsAuthorIdentifierType $authorIdentifierType, string $vatUeIdentifier, string $euEntityName, string $authorizedFingerprintIdentifier, EuEntityPermissionsQueryPermissionType $permissionScope, string $description, \DateTime $startDate)
    {
        $this->id = $id;
        $this->authorIdentifier = $authorIdentifier;
        $this->authorIdentifierType = $authorIdentifierType;
        $this->vatUeIdentifier = $vatUeIdentifier;
        $this->euEntityName = $euEntityName;
        $this->authorizedFingerprintIdentifier = $authorizedFingerprintIdentifier;
        $this->permissionScope = $permissionScope;
        $this->description = $description;
        $this->startDate = $startDate;
    }
}