<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class ExportInvoicesResponse
{
    /**
     * Numer referencyjny operacji.
     *
     * @var ?string $operationReferenceNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('operationReferenceNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $operationReferenceNumber = null;

    /**
     * @param  ?string  $operationReferenceNumber
     * @phpstan-pure
     */
    public function __construct(?string $operationReferenceNumber = null)
    {
        $this->operationReferenceNumber = $operationReferenceNumber;
    }
}