<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


/**
 * FormCode - Struktura dokumentu faktury.
 *
 *
 * Obsługiwane schematy:
 * | SystemCode | SchemaVersion | Value |
 * | --- | --- | --- |
 * | FA (2) | 1-0E | FA |
 * | FA (3) | 1-0E | FA |
 *
 */
class FormCode
{
    /**
     * Kod systemowy
     *
     * @var string $systemCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('systemCode')]
    public string $systemCode;

    /**
     * Wersja schematu
     *
     * @var string $schemaVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('schemaVersion')]
    public string $schemaVersion;

    /**
     * Wartość
     *
     * @var string $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    public string $value;

    /**
     * @param  string  $systemCode
     * @param  string  $schemaVersion
     * @param  string  $value
     * @phpstan-pure
     */
    public function __construct(string $systemCode, string $schemaVersion, string $value)
    {
        $this->systemCode = $systemCode;
        $this->schemaVersion = $schemaVersion;
        $this->value = $value;
    }
}