<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class GenerateTokenResponse
{
    /**
     * Numer referencyjny tokena KSeF. Za jego pomocą można sprawdzić jego status lub go unieważnić.
     *
     * @var ?string $referenceNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('referenceNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $referenceNumber = null;

    /**
     * Token KSeF.
     *
     * @var ?string $token
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('token')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $token = null;

    /**
     * @param  ?string  $referenceNumber
     * @param  ?string  $token
     * @phpstan-pure
     */
    public function __construct(?string $referenceNumber = null, ?string $token = null)
    {
        $this->referenceNumber = $referenceNumber;
        $this->token = $token;
    }
}