<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class GenerateTokenRequest
{
    /**
     * Uprawnienia przypisane tokenowi.
     *
     * @var ?array<TokenPermissionType> $permissions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permissions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\TokenPermissionType>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $permissions = null;

    /**
     * Opis tokena.
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * @param  ?array<TokenPermissionType>  $permissions
     * @param  ?string  $description
     * @phpstan-pure
     */
    public function __construct(?array $permissions = null, ?string $description = null)
    {
        $this->permissions = $permissions;
        $this->description = $description;
    }
}