<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


/** Identifier - Identyfikator nabywcy. */
class Identifier
{
    /**
     * Typ identyfikatora nabywcy.
     *
     * | Wartość | Opis |
     * | --- | --- |
     * | None | Brak identyfikatora nabywcy |
     * | Other | Inny |
     * | Nip | NIP |
     * | VatUe | VAT UE |
     *
     *
     * @var BuyerIdentifierType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\BuyerIdentifierType')]
    public BuyerIdentifierType $type;

    /**
     * Wartośc identyfikatora nabywcy.
     *
     * @var ?string $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $value = null;

    /**
     * @param  BuyerIdentifierType  $type
     * @param  ?string  $value
     * @phpstan-pure
     */
    public function __construct(BuyerIdentifierType $type, ?string $value = null)
    {
        $this->type = $type;
        $this->value = $value;
    }
}