<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class InvoiceMetadataThirdSubjectIdentifier
{
    /**
     * Typ identyfikatora podmiotu trzeciego.
     *
     * | Wartość | Opis |
     * | --- | --- |
     * | Nip | Nip |
     * | InternalId | Identyfikator wewnętrzny |
     * | VatUe | VAT UE |
     * | Other | Inny identyfikator |
     * | None | Brak identyfikatora podmiotu trzeciego |
     *
     *
     * @var ThirdSubjectIdentifierType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\ThirdSubjectIdentifierType')]
    public ThirdSubjectIdentifierType $type;

    /**
     * Wartość identyfikatora podmiotu trzeciego.
     *
     * @var ?string $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $value = null;

    /**
     * @param  ThirdSubjectIdentifierType  $type
     * @param  ?string  $value
     * @phpstan-pure
     */
    public function __construct(ThirdSubjectIdentifierType $type, ?string $value = null)
    {
        $this->type = $type;
        $this->value = $value;
    }
}