<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class InvoiceMetadataThirdSubject
{
    /**
     * Identyfikator podmiotu trzeciego.
     *
     * @var InvoiceMetadataThirdSubjectIdentifier $identifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\InvoiceMetadataThirdSubjectIdentifier')]
    public InvoiceMetadataThirdSubjectIdentifier $identifier;

    /**
     * Rola podmiotu trzeciego.
     *
     * @var int $role
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('role')]
    public int $role;

    /**
     * Nazwa podmiotu trzeciego.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * @param  InvoiceMetadataThirdSubjectIdentifier  $identifier
     * @param  int  $role
     * @param  ?string  $name
     * @phpstan-pure
     */
    public function __construct(InvoiceMetadataThirdSubjectIdentifier $identifier, int $role, ?string $name = null)
    {
        $this->identifier = $identifier;
        $this->role = $role;
        $this->name = $name;
    }
}