<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


/**
 * | Wartość | Opis |
 *
 * | --- | --- |
 * | Subject1 | Podmiot 1 |
 * | Subject2 | Podmiot 2 |
 * | Subject3 | Podmiot 3 |
 * | SubjectAuthorized | Podmiot upoważniony |
 *
 */
enum InvoiceQuerySubjectType: string
{
    case Subject1 = 'Subject1';
    case Subject2 = 'Subject2';
    case Subject3 = 'Subject3';
    case SubjectAuthorized = 'SubjectAuthorized';
}
