<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class InvoicesExportStatusResponse
{
    /**
     * Informacje o aktualnym statusie przetwarzania zapytania.
     *
     * @var StatusInfo $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\StatusInfo')]
    public StatusInfo $status;

    /**
     * Data przetworzenia zapytania
     *
     * @var ?\DateTime $completedDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('completedDate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $completedDate = null;

    /**
     * Informacje o paczce faktur.
     *
     * @var ?Package $package
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('package')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\Package|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Package $package = null;

    /**
     * @param  StatusInfo  $status
     * @param  ?\DateTime  $completedDate
     * @param  ?Package  $package
     * @phpstan-pure
     */
    public function __construct(StatusInfo $status, ?\DateTime $completedDate = null, ?Package $package = null)
    {
        $this->status = $status;
        $this->completedDate = $completedDate;
        $this->package = $package;
    }
}