<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


/**
 * | Wartość | Opis |
 *
 * | --- | --- |
 * | Vat | (FA) Podstawowa |
 * | Zal | (FA) Zaliczkowa |
 * | Kor | (FA) Korygująca |
 * | Roz | (FA) Rozliczeniowa |
 * | Upr | (FA) Uproszczona |
 * | KorZal | (FA) Korygująca fakturę zaliczkową |
 * | KorRoz | (FA) Korygująca fakturę rozliczeniową |
 * | VatPef | [Mock] (PEF) Podstawowowa |
 * | VatPefSp | [Mock] (PEF) Specjalizowana |
 * | KorPef | [Mock] (PEF) Korygująca |
 * | VatRr | [Mock] (RR) Podstawowa |
 * | KorVatRr | [Mock] (RR) Korygująca |
 *
 */
enum InvoiceMetadataInvoiceType: string
{
    case Vat = 'Vat';
    case Zal = 'Zal';
    case Kor = 'Kor';
    case Roz = 'Roz';
    case Upr = 'Upr';
    case KorZal = 'KorZal';
    case KorRoz = 'KorRoz';
    case VatPef = 'VatPef';
    case VatPefSp = 'VatPefSp';
    case KorPef = 'KorPef';
    case VatRr = 'VatRr';
    case KorVatRr = 'KorVatRr';
}
