<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class InvoicePackagePart
{
    /**
     * Numer porządkowy pliku w ramach całego zbioru wynikowego.
     *
     * @var int $ordinalNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ordinalNumber')]
    public int $ordinalNumber;

    /**
     * Metoda HTTP, której należy użyć przy pobieraniu pliku.
     *
     * @var string $method
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('method')]
    public string $method;

    /**
     * Adres URL, pod który należy wysłać żądanie pobrania pliku.
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * Data wygaśnięcia linku do pobrania pliku.
     *
     * @var \DateTime $expirationDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expirationDate')]
    public \DateTime $expirationDate;

    /**
     * Nagłówki, których należy użyć przy pobieraniu pliku.
     *
     * @var array<string, ?string> $headers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('headers')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string|null>')]
    public array $headers;

    /**
     * Nazwa pliku.
     *
     * @var string $fileName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fileName')]
    public string $fileName;

    /**
     * @param  int  $ordinalNumber
     * @param  string  $method
     * @param  string  $url
     * @param  \DateTime  $expirationDate
     * @param  array<string, ?string>  $headers
     * @param  string  $fileName
     * @phpstan-pure
     */
    public function __construct(int $ordinalNumber, string $method, string $url, \DateTime $expirationDate, string $fileName, ?array $headers = [])
    {
        $this->ordinalNumber = $ordinalNumber;
        $this->method = $method;
        $this->url = $url;
        $this->expirationDate = $expirationDate;
        $this->headers = $headers;
        $this->fileName = $fileName;
    }
}