<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class OpenBatchSessionResponse
{
    /**
     * Numer referencyjny sesji.
     *
     * @var string $referenceNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('referenceNumber')]
    public string $referenceNumber;

    /**
     * Dane wymagane do poprawnego przesłania poszczególnych części pliku paczki faktur.
     *
     * @var array<PartUploadRequest> $partUploadRequests
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('partUploadRequests')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\PartUploadRequest>')]
    public array $partUploadRequests;

    /**
     * @param  string  $referenceNumber
     * @param  array<PartUploadRequest>  $partUploadRequests
     * @phpstan-pure
     */
    public function __construct(string $referenceNumber, array $partUploadRequests)
    {
        $this->referenceNumber = $referenceNumber;
        $this->partUploadRequests = $partUploadRequests;
    }
}