<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class PermissionsOperationResponse
{
    /**
     * Numer referencyjny asynchronicznej operacji nadawania lub odbierania uprawnień.
     *
     * @var string $operationReferenceNumber
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('operationReferenceNumber')]
    public string $operationReferenceNumber;

    /**
     * Numer referencyjny asynchronicznej operacji nadawania lub odbierania uprawnień.
     *
     * @var string $referenceNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('referenceNumber')]
    public string $referenceNumber;

    /**
     * @param  string  $operationReferenceNumber
     * @param  string  $referenceNumber
     * @phpstan-pure
     */
    public function __construct(string $operationReferenceNumber, string $referenceNumber)
    {
        $this->operationReferenceNumber = $operationReferenceNumber;
        $this->referenceNumber = $referenceNumber;
    }
}