<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


/** PersonPermissionIdDocument - Dane dokumentu tożsamości osoby fizycznej. */
class PersonPermissionIdDocument
{
    /**
     * Rodzaj dokumentu tożsamości.
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * Seria i numer dokumentu tożsamości.
     *
     * @var string $number
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('number')]
    public string $number;

    /**
     * Kraj wydania dokumentu tożsamości.
     *
     * @var string $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    public string $country;

    /**
     * @param  string  $type
     * @param  string  $number
     * @param  string  $country
     * @phpstan-pure
     */
    public function __construct(string $type, string $number, string $country)
    {
        $this->type = $type;
        $this->number = $number;
        $this->country = $country;
    }
}