<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class PersonCreateRequest
{
    /**
     *
     * @var ?bool $isBailiff
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('isBailiff')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $isBailiff = null;

    /**
     *
     * @var ?string $nip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nip')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $nip = null;

    /**
     *
     * @var ?string $pesel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pesel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $pesel = null;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     *
     * @var ?\DateTime $createdDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdDate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdDate = null;

    /**
     * @param  ?bool  $isBailiff
     * @param  ?string  $nip
     * @param  ?string  $pesel
     * @param  ?string  $description
     * @param  ?\DateTime  $createdDate
     * @phpstan-pure
     */
    public function __construct(?bool $isBailiff = null, ?string $nip = null, ?string $pesel = null, ?string $description = null, ?\DateTime $createdDate = null)
    {
        $this->isBailiff = $isBailiff;
        $this->nip = $nip;
        $this->pesel = $pesel;
        $this->description = $description;
        $this->createdDate = $createdDate;
    }
}