<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


/** Typ identyfikatora podmiotu docelowego. */
enum PersonalPermissionTargetIdentifierType: string
{
    case Nip = 'Nip';
    case AllPartners = 'AllPartners';
}
