<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class QueryInvoicesMetadataReponse
{
    /**
     * Całkowita liczba pasujących rekordów w repozytorium.
     *
     * @var int $totalCount
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalCount')]
    public int $totalCount;

    /**
     * Flaga informująca o dostępności kolejnej strony wyników.
     *
     * @var bool $hasMore
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasMore')]
    public bool $hasMore;

    /**
     * Lista faktur spełniających kryteria.
     *
     * @var array<InvoiceMetadata> $invoices
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoices')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\InvoiceMetadata>')]
    public array $invoices;

    /**
     * @param  int  $totalCount
     * @param  bool  $hasMore
     * @param  array<InvoiceMetadata>  $invoices
     * @phpstan-pure
     */
    public function __construct(int $totalCount, bool $hasMore, array $invoices)
    {
        $this->totalCount = $totalCount;
        $this->hasMore = $hasMore;
        $this->invoices = $invoices;
    }
}