<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class QueryInvoicesMetadataResponse
{
    /**
     * Określa, czy istnieją kolejne wyniki zapytania.
     *
     * @var bool $hasMore
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasMore')]
    public bool $hasMore;

    /**
     * Określa, czy osiągnięto maksymalny dopuszczalny zakres wyników zapytania (10 000).
     *
     * @var bool $isTruncated
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('isTruncated')]
    public bool $isTruncated;

    /**
     * Lista faktur spełniających kryteria.
     *
     * @var array<InvoiceMetadata> $invoices
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoices')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\InvoiceMetadata>')]
    public array $invoices;

    /**
     * @param  bool  $hasMore
     * @param  bool  $isTruncated
     * @param  array<InvoiceMetadata>  $invoices
     * @phpstan-pure
     */
    public function __construct(bool $hasMore, bool $isTruncated, array $invoices)
    {
        $this->hasMore = $hasMore;
        $this->isTruncated = $isTruncated;
        $this->invoices = $invoices;
    }
}