<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class QueryInvoicesMetadataResponse
{
    /**
     * Flaga informująca o dostępności kolejnej strony wyników.
     *
     * @var bool $hasMore
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasMore')]
    public bool $hasMore;

    /**
     * Lista faktur spełniających kryteria.
     *
     * @var array<InvoiceMetadata> $invoices
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoices')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\InvoiceMetadata>')]
    public array $invoices;

    /**
     * @param  bool  $hasMore
     * @param  array<InvoiceMetadata>  $invoices
     * @phpstan-pure
     */
    public function __construct(bool $hasMore, array $invoices)
    {
        $this->hasMore = $hasMore;
        $this->invoices = $invoices;
    }
}