<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


/** Seller - Dane identyfikujące sprzedawcę. */
class Seller
{
    /**
     * Nip sprzedawcy.
     *
     * @var string $nip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('nip')]
    public string $nip;

    /**
     * Identyfikator sprzedawcy.
     *
     * @var ?string $identifier
     * @deprecated  field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $identifier = null;

    /**
     * Nazwa sprzedawcy.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * @param  string  $nip
     * @param  ?string  $identifier
     * @param  ?string  $name
     * @phpstan-pure
     */
    public function __construct(string $nip, ?string $identifier = null, ?string $name = null)
    {
        $this->nip = $nip;
        $this->identifier = $identifier;
        $this->name = $name;
    }
}