<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class SessionInvoiceStatusResponse
{
    /**
     * Numer sekwencyjny faktury w ramach sesji.
     *
     * @var int $ordinalNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ordinalNumber')]
    public int $ordinalNumber;

    /**
     * Data przyjęcia faktury w systemie KSeF (do dalszego przetwarzania).
     *
     * @var \DateTime $invoicingDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoicingDate')]
    public \DateTime $invoicingDate;

    /**
     * Status faktury.
     *
     *
     * | Code | Description | Details |
     * | --- | --- | --- |
     * | 100 | Faktura przyjęta do dalszego przetwarzania | - |
     * | 150 | Trwa przetwarzanie | - |
     * | 200 | Sukces | - |
     * | 405 | Przetwarzanie anulowane | - |
     * | 410 | Nieprawidłowy zakres uprawnień | - |
     * | 415 | Brak możliwości wysyłania faktury z załącznikiem | - |
     * | 430 | Błąd weryfikacji pliku faktury | - |
     * | 435 | Błąd odszyfrowania pliku | - |
     * | 440 | Duplikat faktury | - |
     * | 450 | Błąd weryfikacji semantyki dokumentu faktury | - |
     * | 500 | Nieznany błąd ({statusCode}) | - |
     *
     * @var StatusInfo $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\StatusInfo')]
    public StatusInfo $status;

    /**
     * Numer faktury.
     *
     * @var ?string $invoiceNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoiceNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $invoiceNumber = null;

    /**
     * Numer KSeF.
     *
     * @var ?string $ksefNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ksefNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ksefNumber = null;

    /**
     * Numer referencyjny faktury.
     *
     * @var ?string $referenceNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('referenceNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $referenceNumber = null;

    /**
     * Skrót SHA256 faktury, zakodowany w formacie Base64.
     *
     * @var ?string $invoiceHash
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoiceHash')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $invoiceHash = null;

    /**
     * Nazwa pliku faktury (zwracana dla faktur wysyłanych wsadowo).
     *
     * @var ?string $invoiceFileName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoiceFileName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $invoiceFileName = null;

    /**
     * Data nadania numeru KSeF.
     *
     * @var ?\DateTime $acquisitionDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('acquisitionDate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $acquisitionDate = null;

    /**
     * Data trwałego zapisu faktury w repozytorium systemu KSeF.
     *
     * @var ?\DateTime $permanentStorageDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permanentStorageDate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $permanentStorageDate = null;

    /**
     * Adres do pobrania UPO.
     *
     * @var ?string $upoDownloadUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('upoDownloadUrl')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $upoDownloadUrl = null;

    /**
     * Tryb fakturowania (online/offline).
     *
     * @var ?SessionInvoiceStatusResponseInvoicingMode $invoicingMode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoicingMode')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\SessionInvoiceStatusResponseInvoicingMode|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SessionInvoiceStatusResponseInvoicingMode $invoicingMode = null;

    /**
     * @param  int  $ordinalNumber
     * @param  \DateTime  $invoicingDate
     * @param  StatusInfo  $status
     * @param  ?string  $invoiceNumber
     * @param  ?string  $ksefNumber
     * @param  ?string  $referenceNumber
     * @param  ?string  $invoiceHash
     * @param  ?string  $invoiceFileName
     * @param  ?\DateTime  $acquisitionDate
     * @param  ?\DateTime  $permanentStorageDate
     * @param  ?string  $upoDownloadUrl
     * @param  ?SessionInvoiceStatusResponseInvoicingMode  $invoicingMode
     * @phpstan-pure
     */
    public function __construct(int $ordinalNumber, \DateTime $invoicingDate, StatusInfo $status, ?string $invoiceNumber = null, ?string $ksefNumber = null, ?string $referenceNumber = null, ?string $invoiceHash = null, ?string $invoiceFileName = null, ?\DateTime $acquisitionDate = null, ?\DateTime $permanentStorageDate = null, ?string $upoDownloadUrl = null, ?SessionInvoiceStatusResponseInvoicingMode $invoicingMode = null)
    {
        $this->ordinalNumber = $ordinalNumber;
        $this->invoicingDate = $invoicingDate;
        $this->status = $status;
        $this->invoiceNumber = $invoiceNumber;
        $this->ksefNumber = $ksefNumber;
        $this->referenceNumber = $referenceNumber;
        $this->invoiceHash = $invoiceHash;
        $this->invoiceFileName = $invoiceFileName;
        $this->acquisitionDate = $acquisitionDate;
        $this->permanentStorageDate = $permanentStorageDate;
        $this->upoDownloadUrl = $upoDownloadUrl;
        $this->invoicingMode = $invoicingMode;
    }
}