<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class SetSubjectLimitsRequest
{
    /**
     *
     * @var ?SubjectIdentifierType $subjectIdentifierType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subjectIdentifierType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\SubjectIdentifierType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SubjectIdentifierType $subjectIdentifierType = null;

    /**
     *
     * @var ?SetSubjectLimitsRequestEnrollment $enrollment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enrollment')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\SetSubjectLimitsRequestEnrollment|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SetSubjectLimitsRequestEnrollment $enrollment = null;

    /**
     *
     * @var ?SetSubjectLimitsRequestCertificate $certificate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('certificate')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\SetSubjectLimitsRequestCertificate|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SetSubjectLimitsRequestCertificate $certificate = null;

    /**
     * @param  ?SubjectIdentifierType  $subjectIdentifierType
     * @param  ?SetSubjectLimitsRequestEnrollment  $enrollment
     * @param  ?SetSubjectLimitsRequestCertificate  $certificate
     * @phpstan-pure
     */
    public function __construct(?SubjectIdentifierType $subjectIdentifierType = null, ?SetSubjectLimitsRequestEnrollment $enrollment = null, ?SetSubjectLimitsRequestCertificate $certificate = null)
    {
        $this->subjectIdentifierType = $subjectIdentifierType;
        $this->enrollment = $enrollment;
        $this->certificate = $certificate;
    }
}