<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class SubjectRemoveRequest
{
    /**
     *
     * @var ?string $subjectNip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subjectNip')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $subjectNip = null;

    /**
     * @param  ?string  $subjectNip
     * @phpstan-pure
     */
    public function __construct(?string $subjectNip = null)
    {
        $this->subjectNip = $subjectNip;
    }
}