<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


enum SubjectType: string
{
    case EnforcementAuthority = 'EnforcementAuthority';
    case VatGroup = 'VatGroup';
    case Jst = 'JST';
}
