<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class SubjectCreateRequest
{
    /**
     *
     * @var ?SubjectType $subjectType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subjectType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\SubjectType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SubjectType $subjectType = null;

    /**
     *
     * @var ?string $subjectNip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subjectNip')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $subjectNip = null;

    /**
     * $subunits
     *
     * @var ?array<Subunit> $subunits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subunits')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\Subunit>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $subunits = null;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     *
     * @var ?\DateTime $createdDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdDate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $createdDate = null;

    /**
     * @param  ?SubjectType  $subjectType
     * @param  ?string  $subjectNip
     * @param  ?array<Subunit>  $subunits
     * @param  ?string  $description
     * @param  ?\DateTime  $createdDate
     * @phpstan-pure
     */
    public function __construct(?SubjectType $subjectType = null, ?string $subjectNip = null, ?array $subunits = null, ?string $description = null, ?\DateTime $createdDate = null)
    {
        $this->subjectType = $subjectType;
        $this->subjectNip = $subjectNip;
        $this->subunits = $subunits;
        $this->description = $description;
        $this->createdDate = $createdDate;
    }
}