<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class SubordinateEntityRolesQueryRequest
{
    /**
     * Identyfikator podmiotu podrzędnego.
     *
     * | Type | Value |
     * | --- | --- |
     * | Nip | 10 cyfrowy numer NIP |
     *
     * @var ?SubordinateEntityIdentifier $subordinateEntityIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subordinateEntityIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\SubordinateEntityIdentifier|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?SubordinateEntityIdentifier $subordinateEntityIdentifier = null;

    /**
     * @param  ?SubordinateEntityIdentifier  $subordinateEntityIdentifier
     * @phpstan-pure
     */
    public function __construct(?SubordinateEntityIdentifier $subordinateEntityIdentifier = null)
    {
        $this->subordinateEntityIdentifier = $subordinateEntityIdentifier;
    }
}