<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class SubordinateEntityRole
{
    /**
     * Identyfikator podmiotu podrzędnego.
     *
     * @var string $subordinateEntityIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subordinateEntityIdentifier')]
    public string $subordinateEntityIdentifier;

    /**
     * Typ identyfikatora podmiotu podrzędnego.
     *
     * @var SubordinateRoleSubordinateEntityIdentifierType $subordinateEntityIdentifierType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subordinateEntityIdentifierType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\SubordinateRoleSubordinateEntityIdentifierType')]
    public SubordinateRoleSubordinateEntityIdentifierType $subordinateEntityIdentifierType;

    /**
     * Powiązanie.
     *
     * @var SubordinateEntityRoleType $role
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('role')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\SubordinateEntityRoleType')]
    public SubordinateEntityRoleType $role;

    /**
     * Opis.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * Data rozpoczęcia obowiązywania powiązania.
     *
     * @var \DateTime $startDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('startDate')]
    public \DateTime $startDate;

    /**
     * @param  string  $subordinateEntityIdentifier
     * @param  SubordinateRoleSubordinateEntityIdentifierType  $subordinateEntityIdentifierType
     * @param  SubordinateEntityRoleType  $role
     * @param  string  $description
     * @param  \DateTime  $startDate
     * @phpstan-pure
     */
    public function __construct(string $subordinateEntityIdentifier, SubordinateRoleSubordinateEntityIdentifierType $subordinateEntityIdentifierType, SubordinateEntityRoleType $role, string $description, \DateTime $startDate)
    {
        $this->subordinateEntityIdentifier = $subordinateEntityIdentifier;
        $this->subordinateEntityIdentifierType = $subordinateEntityIdentifierType;
        $this->role = $role;
        $this->description = $description;
        $this->startDate = $startDate;
    }
}