<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class Subunit
{
    /**
     *
     * @var string $subjectNip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subjectNip')]
    public string $subjectNip;

    /**
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * @param  string  $subjectNip
     * @param  string  $description
     * @phpstan-pure
     */
    public function __construct(string $subjectNip, string $description)
    {
        $this->subjectNip = $subjectNip;
        $this->description = $description;
    }
}