<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class TestDataPermissionsRevokeRequest
{
    /**
     *
     * @var ?TestDataPermissionsRevokeRequestContextIdentifier $contextIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contextIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\TestDataPermissionsRevokeRequestContextIdentifier|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TestDataPermissionsRevokeRequestContextIdentifier $contextIdentifier = null;

    /**
     *
     * @var ?TestDataPermissionsRevokeRequestAuthorizedIdentifier $authorizedIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorizedIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\TestDataPermissionsRevokeRequestAuthorizedIdentifier|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TestDataPermissionsRevokeRequestAuthorizedIdentifier $authorizedIdentifier = null;

    /**
     * @param  ?TestDataPermissionsRevokeRequestContextIdentifier  $contextIdentifier
     * @param  ?TestDataPermissionsRevokeRequestAuthorizedIdentifier  $authorizedIdentifier
     * @phpstan-pure
     */
    public function __construct(?TestDataPermissionsRevokeRequestContextIdentifier $contextIdentifier = null, ?TestDataPermissionsRevokeRequestAuthorizedIdentifier $authorizedIdentifier = null)
    {
        $this->contextIdentifier = $contextIdentifier;
        $this->authorizedIdentifier = $authorizedIdentifier;
    }
}