<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


enum TestDataPermissionType: string
{
    case InvoiceRead = 'InvoiceRead';
    case InvoiceWrite = 'InvoiceWrite';
    case Introspection = 'Introspection';
    case CredentialsRead = 'CredentialsRead';
    case CredentialsManage = 'CredentialsManage';
    case EnforcementOperations = 'EnforcementOperations';
    case SubunitManage = 'SubunitManage';
}
