<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class TestDataPermission
{
    /**
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     *
     * @var TestDataPermissionType $permissionType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permissionType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\TestDataPermissionType')]
    public TestDataPermissionType $permissionType;

    /**
     * @param  string  $description
     * @param  TestDataPermissionType  $permissionType
     * @phpstan-pure
     */
    public function __construct(string $description, TestDataPermissionType $permissionType)
    {
        $this->description = $description;
        $this->permissionType = $permissionType;
    }
}