<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class TestDataPermission
{
    /**
     *
     * @var ?TestDataPermissionType $permissionType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permissionType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\TestDataPermissionType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TestDataPermissionType $permissionType = null;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * @param  ?TestDataPermissionType  $permissionType
     * @param  ?string  $description
     * @phpstan-pure
     */
    public function __construct(?TestDataPermissionType $permissionType = null, ?string $description = null)
    {
        $this->permissionType = $permissionType;
        $this->description = $description;
    }
}