<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class TestDataPermissionsGrantRequest
{
    /**
     *
     * @var ?TestDataPermissionsGrantRequestContextIdentifier $contextIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contextIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\TestDataPermissionsGrantRequestContextIdentifier|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TestDataPermissionsGrantRequestContextIdentifier $contextIdentifier = null;

    /**
     *
     * @var ?TestDataPermissionsGrantRequestAuthorizedIdentifier $authorizedIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('authorizedIdentifier')]
    #[\Speakeasy\Serializer\Annotation\Type('\Intermedia\Ksef\Apiv2\Models\Components\TestDataPermissionsGrantRequestAuthorizedIdentifier|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TestDataPermissionsGrantRequestAuthorizedIdentifier $authorizedIdentifier = null;

    /**
     * $permissions
     *
     * @var ?array<TestDataPermission> $permissions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permissions')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Intermedia\Ksef\Apiv2\Models\Components\TestDataPermission>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $permissions = null;

    /**
     * @param  ?TestDataPermissionsGrantRequestContextIdentifier  $contextIdentifier
     * @param  ?TestDataPermissionsGrantRequestAuthorizedIdentifier  $authorizedIdentifier
     * @param  ?array<TestDataPermission>  $permissions
     * @phpstan-pure
     */
    public function __construct(?TestDataPermissionsGrantRequestContextIdentifier $contextIdentifier = null, ?TestDataPermissionsGrantRequestAuthorizedIdentifier $authorizedIdentifier = null, ?array $permissions = null)
    {
        $this->contextIdentifier = $contextIdentifier;
        $this->authorizedIdentifier = $authorizedIdentifier;
        $this->permissions = $permissions;
    }
}