<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


/**
 * | Wartość | Opis |
 *
 * | --- | --- |
 * | Nip | Nip |
 * | InternalId | Identyfikator wewnętrzny |
 * | VatUe | VAT UE |
 * | Other | Inny identyfikator |
 * | None | Brak identyfikatora podmiotu trzeciego |
 *
 */
enum ThirdSubjectIdentifierType: string
{
    case Nip = 'Nip';
    case InternalId = 'InternalId';
    case VatUe = 'VatUe';
    case Other = 'Other';
    case None = 'None';
}
