<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2\Models\Components;


class UpoPageResponse
{
    /**
     * Numer referencyjny strony UPO.
     *
     * @var string $referenceNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('referenceNumber')]
    public string $referenceNumber;

    /**
     * Adres do pobrania strony UPO.
     *
     * @var string $downloadUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('downloadUrl')]
    public string $downloadUrl;

    /**
     * @param  string  $referenceNumber
     * @param  string  $downloadUrl
     * @phpstan-pure
     */
    public function __construct(string $referenceNumber, string $downloadUrl)
    {
        $this->referenceNumber = $referenceNumber;
        $this->downloadUrl = $downloadUrl;
    }
}