<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Intermedia\Ksef\Apiv2;



/**
 * Client - KSeF API TE: **Wersja API:** 2.0.0 (build 2.0.0-rc5-te-20250925.4+c6f3445dc0dbc0f8449a2dcef51bda25b3915d0d)<br>
 *
 * **Klucze publiczne** Ministerstwa Finansów (dla danego środowiska): [Pobierz klucze](#tag/Certyfikaty-klucza-publicznego)<br>
 * **Historia zmian:** [Changelog](https://github.com/CIRFMF/ksef-docs/blob/main/api-changelog.md)<br>
 * **Rozszerzona dokumentacja API:** [ksef-docs](https://github.com/CIRFMF/ksef-docs/tree/main)
 *
 */
class Client
{
    public const SERVERS = [
        'https://ksef-test.mf.gov.pl',
    ];

    public Auth $auth;

    public Certificates $certificates;

    public Security $security;

    public TestData $testData;

    public Permissions $permissions;

    public GetInvoices $getInvoices;

    public Sessions $sessions;

    public Invoices $invoices;

    public Tokens $tokens;

    public Peppol $peppol;

    /**
     * Returns a new instance of the SDK builder used to configure and create the SDK instance.
     *
     * @return ClientBuilder
     */
    public static function builder(): ClientBuilder
    {
        return new ClientBuilder();
    }

    /**
     * @param  SDKConfiguration  $sdkConfiguration
     */
    public function __construct(
        public SDKConfiguration $sdkConfiguration,
    ) {
        $this->auth = new Auth($this->sdkConfiguration);
        $this->certificates = new Certificates($this->sdkConfiguration);
        $this->security = new Security($this->sdkConfiguration);
        $this->testData = new TestData($this->sdkConfiguration);
        $this->permissions = new Permissions($this->sdkConfiguration);
        $this->getInvoices = new GetInvoices($this->sdkConfiguration);
        $this->sessions = new Sessions($this->sdkConfiguration);
        $this->invoices = new Invoices($this->sdkConfiguration);
        $this->tokens = new Tokens($this->sdkConfiguration);
        $this->peppol = new Peppol($this->sdkConfiguration);
        $this->initHooks();

    }

    private function initHooks(): void
    {
        $this->sdkConfiguration = $this->sdkConfiguration->hooks->sdkInit($this->sdkConfiguration);
    }
}